window.SCHOLARSHIP_Y8_ARITH_T02 = (() => {
  const frac = (n,d) => `<span class="math-frac" aria-label="${n} over ${d}"><span class="top">${n}</span><span class="bottom">${d}</span></span>`;
  const mixed = (w,n,d) => `<span class="math-mixed"><span>${w}</span>${frac(n,d)}</span>`;

  return [
    {topic:"Percentages", text:"A school has 450 students. 18% are taking part in an inter-school sports day. How many students are taking part?", html:"A school has <b>450 students</b>. <b>18%</b> are taking part in an inter-school sports day. How many students are taking part?", answer:"81"},
    {topic:"Whole Numbers", text:"A fundraising target is $125,000. The school has already raised $68,475. How many dollars are still needed?", html:"A fundraising target is <b>$125,000</b>. The school has already raised <b>$68,475</b>. How many dollars are still needed?", answer:"56525"},
    {topic:"Fractions", text:"Two walking-track sections are 2 5/6 km and 1 7/12 km long. What is their total length?", html:`Two walking-track sections are ${mixed(2,5,6)} km and ${mixed(1,7,12)} km long. What is their total length?`, answer:"4 5/12"},
    {topic:"Speed", text:"A coach travels 195 km in 2 hours 36 minutes. What is its average speed in km/h?", html:"A coach travels <b>195 km</b> in <b>2 hours 36 minutes</b>. What is its average speed in <b>km/h</b>?", answer:"75"},
    {topic:"Factors and Multiples", text:"Two ferries leave a terminal together. One leaves every 20 minutes and the other every 30 minutes. After how many minutes will they next leave together?", html:"Two ferries leave a terminal together. One leaves every <b>20 minutes</b> and the other every <b>30 minutes</b>. After how many minutes will they next leave together?", answer:"60"},
    {topic:"Decimals", text:"Apples cost $4.25 per kilogram. What is the cost of 3.6 kg of apples?", html:"Apples cost <b>$4.25 per kilogram</b>. What is the cost of <b>3.6 kg</b> of apples?", answer:"15.3"},
    {topic:"Surface Area", text:"A closed rectangular gift box measures 8 cm by 5 cm by 3 cm. What is its total surface area in cm²?", html:"A closed rectangular gift box measures <b>8 cm × 5 cm × 3 cm</b>. What is its total surface area in <b>cm²</b>?", answer:"158"},
    {topic:"Reverse Percentages", text:"A school club increased its membership by 25% and now has 90 members. How many members did it have before the increase?", html:"A school club increased its membership by <b>25%</b> and now has <b>90 members</b>. How many members did it have before the increase?", answer:"72"},
    {topic:"Factors and Multiples", text:"A teacher has 96 green counters and 144 yellow counters. She wants the greatest possible number of identical groups, with the same number of each colour in every group and none left over. How many groups can she make?", html:"A teacher has <b>96 green counters</b> and <b>144 yellow counters</b>. She wants the <b>greatest possible number of identical groups</b>, with the same number of each colour in every group and none left over. How many groups can she make?", answer:"48"},
    {topic:"Directed Numbers", text:"The temperature was −12°C in the evening. Overnight it fell by another 17°C. What was the temperature after the fall?", html:"The temperature was <b>−12°C</b> in the evening. Overnight it fell by another <b>17°C</b>. What was the temperature after the fall?", answer:"-29"},

    {topic:"Fractions", text:"A drink container holds 1 1/2 L. Each cup holds 3/16 L. How many full cups can be filled?", html:`A drink container holds ${mixed(1,1,2)} L. Each cup holds ${frac(3,16)} L. How many <b>full cups</b> can be filled?`, answer:"8"},
    {topic:"Rounding", text:"A stadium recorded 526,481 visitors during a season. Round this number to 3 significant figures.", html:"A stadium recorded <b>526,481</b> visitors during a season. Round this number to <b>3 significant figures</b>.", answer:"526000"},
    {topic:"Ratio", text:"A $315 prize fund is shared in the ratio 4 : 3 : 2. What is the largest share?", html:"A <b>$315</b> prize fund is shared in the ratio <b>4 : 3 : 2</b>. What is the largest share?", answer:"140"},
    {topic:"Measurement", text:"A display panel has an area of 1.84 m². What is this area in cm²?", html:"A display panel has an area of <b>1.84 m²</b>. What is this area in <b>cm²</b>?", answer:"18400"},
    {topic:"Multiplication", text:"A warehouse sends 326 cartons, with 28 notebooks in each carton. How many notebooks are sent altogether?", html:"A warehouse sends <b>326 cartons</b>, with <b>28 notebooks</b> in each carton. How many notebooks are sent altogether?", answer:"9128"},
    {topic:"Decimals", text:"A tank contains 24 L of water. If 8.735 L is used, how many litres remain?", html:"A tank contains <b>24 L</b> of water. If <b>8.735 L</b> is used, how many litres remain?", answer:"15.265"},
    {topic:"Data", text:"Six quiz scores have a mean of 18. Five of the scores are 12, 16, 17, 20 and 21. What is the sixth score?", html:"Six quiz scores have a <b>mean of 18</b>. Five of the scores are <b>12, 16, 17, 20 and 21</b>. What is the sixth score?", answer:"22"},
    {topic:"Prime Factors", text:"A competition has 374 students. They must be divided into equal-sized teams, and the number of students in each team must be a prime number. What is the largest possible team size?", html:"A competition has <b>374 students</b>. They must be divided into equal-sized teams, and the number of students in each team must be a <b>prime number</b>. What is the largest possible team size?", answer:"17"},
    {topic:"Fractions", text:"5/6 of a garden is planted. 3/10 of the planted section is roses. What fraction of the whole garden is planted with roses?", html:`${frac(5,6)} of a garden is planted. ${frac(3,10)} of the planted section is roses. What fraction of the <b>whole garden</b> is planted with roses?`, answer:"1/4"},
    {topic:"Circle Area", text:"A circular lawn has radius 10.5 m. Using π = 22/7, what is its area in m²?", html:`A circular lawn has radius <b>10.5 m</b>. Using π = ${frac(22,7)}, what is its area in <b>m²</b>?`, answer:"346.5"},

    {topic:"Percentage Change", text:"The number of entries in a school event increased from 320 to 368. What was the percentage increase? Enter the number only.", html:"The number of entries in a school event increased from <b>320</b> to <b>368</b>. What was the <b>percentage increase</b>? Enter the number only.", answer:"15"},
    {topic:"Division", text:"A printer produces 11,760 pages and bundles them equally into packs of 56 pages. How many packs are made?", html:"A printer produces <b>11,760 pages</b> and bundles them equally into packs of <b>56 pages</b>. How many packs are made?", answer:"210"},
    {topic:"Fractions", text:"A roll of fabric is 5 1/8 m long. A piece 2 5/6 m long is used. How many metres remain?", html:`A roll of fabric is ${mixed(5,1,8)} m long. A piece ${mixed(2,5,6)} m long is used. How many metres remain?`, answer:"2 7/24"},
    {topic:"Scale", text:"On a map with scale 1 : 50,000, two locations are 6.8 cm apart. What is the real distance in kilometres?", html:"On a map with scale <b>1 : 50,000</b>, two locations are <b>6.8 cm</b> apart. What is the real distance in <b>kilometres</b>?", answer:"3.4"},
    {topic:"Capacity", text:"A container has 3.25 L of juice and another 860 mL is added. How many millilitres are there altogether?", html:"A container has <b>3.25 L</b> of juice and another <b>860 mL</b> is added. How many <b>millilitres</b> are there altogether?", answer:"4110"},
    {topic:"Indices", text:"A computer process begins with 3 tasks. At each stage the number of tasks doubles. After five doublings, how many tasks are there?", html:"A computer process begins with <b>3 tasks</b>. At each stage the number of tasks <b>doubles</b>. After <b>five doublings</b>, how many tasks are there?", answer:"96"},
    {topic:"Decimals", text:"A supplier has 9.45 kg of spice and packs it into 0.27 kg bags. How many full bags can be made?", html:"A supplier has <b>9.45 kg</b> of spice and packs it into <b>0.27 kg</b> bags. How many full bags can be made?", answer:"35"},
    {topic:"Percentages", text:"A bicycle costs $250. It is reduced by 12%, then the reduced price is increased by 5%. What is the final price?", html:"A bicycle costs <b>$250</b>. It is reduced by <b>12%</b>, then the reduced price is increased by <b>5%</b>. What is the final price?", answer:"231"},
    {topic:"Square Roots", text:"A square sports court has an area of 1296 m². What is the length of one side?", html:"A square sports court has an area of <b>1296 m²</b>. What is the length of one side?", answer:"36"},
    {topic:"Time", text:"A journey takes 1 hour 55 minutes before lunch and 2 hours 37 minutes after lunch. How many minutes of travel is this altogether?", html:"A journey takes <b>1 hour 55 minutes</b> before lunch and <b>2 hours 37 minutes</b> after lunch. How many <b>minutes</b> of travel is this altogether?", answer:"272"},

    {topic:"Factors", text:"All 90 students must be arranged in equal rows with no students left over. How many different positive whole-number choices are there for the number of rows?", html:"All <b>90 students</b> must be arranged in equal rows with no students left over. How many different <b>positive whole-number</b> choices are there for the number of rows?", answer:"12"},
    {topic:"Fractions", text:"In a music club, 75 students make up 5/8 of all members. How many students are in the club altogether?", html:`In a music club, <b>75 students</b> make up ${frac(5,8)} of all members. How many students are in the club altogether?`, answer:"120"},
    {topic:"Triangle Area", text:"A triangular banner has base 15.6 cm and perpendicular height 9.5 cm. What is its area in cm²?", html:"A triangular banner has base <b>15.6 cm</b> and perpendicular height <b>9.5 cm</b>. What is its area in <b>cm²</b>?", answer:"74.1"},
    {topic:"Fractions and Decimals", text:"In a quality check, 84 out of every 1000 items are faulty. What fraction of the batch is faulty? Give your answer in simplest form.", html:"In a quality check, <b>84 out of every 1000 items</b> are faulty. What fraction of the batch is faulty? Give your answer in <b>simplest form</b>.", answer:"21/250", answerFormat:"fractionSimplest"},
    {topic:"Order of Operations", text:"A school has 150 event tickets. It keeps 30 tickets for staff and shares the rest equally among 8 classes. How many tickets does each class receive?", html:"A school has <b>150 event tickets</b>. It keeps <b>30 tickets</b> for staff and shares the rest equally among <b>8 classes</b>. How many tickets does each class receive?", answer:"15"},
    {topic:"Rate", text:"A 6.4 kg box of fruit costs $22.40. What is the cost per kilogram?", html:"A <b>6.4 kg</b> box of fruit costs <b>$22.40</b>. What is the cost per kilogram?", answer:"3.5"},
    {topic:"Whole Numbers", text:"A museum had 67,895 visitors in one term and 28,764 in the next term. How many visitors were recorded altogether?", html:"A museum had <b>67,895</b> visitors in one term and <b>28,764</b> in the next term. How many visitors were recorded altogether?", answer:"96659"},
    {topic:"Volume", text:"A rectangular storage container is 9.5 cm long, 6 cm wide and 4 cm high. What is its volume in cm³?", html:"A rectangular storage container is <b>9.5 cm</b> long, <b>6 cm</b> wide and <b>4 cm</b> high. What is its volume in <b>cm³</b>?", answer:"228"},
    {topic:"Fractions", text:"A tank is 13/15 full. Water equal to 7/20 of the tank's capacity is used. What fraction of the tank is still full?", html:`A tank is ${frac(13,15)} full. Water equal to ${frac(7,20)} of the tank's capacity is used. What fraction of the tank is still full?`, answer:"31/60"},
    {topic:"Rounding", text:"A laboratory measurement is 0.006784 g. Round it to 2 significant figures.", html:"A laboratory measurement is <b>0.006784 g</b>. Round it to <b>2 significant figures</b>.", answer:"0.0068"},

    {topic:"Reverse Percentages", text:"After a 15% discount, a sports jacket costs $136. What was the original price?", html:"After a <b>15% discount</b>, a sports jacket costs <b>$136</b>. What was the original price?", answer:"160"},
    {topic:"Fractions", text:"A theatre has 240 seats. 3/4 are occupied, and 5/9 of the people seated are children. How many children are seated?", html:`A theatre has <b>240 seats</b>. ${frac(3,4)} are occupied, and ${frac(5,9)} of the people seated are children. How many children are seated?`, answer:"100"},
    {topic:"Decimals", text:"Two parcels have masses of 7.905 kg and 12.68 kg. What is their total mass?", html:"Two parcels have masses of <b>7.905 kg</b> and <b>12.68 kg</b>. What is their total mass?", answer:"20.585"},
    {topic:"Measurement", text:"A bag of rice has a mass of 2.45 kg. What is its mass in grams?", html:"A bag of rice has a mass of <b>2.45 kg</b>. What is its mass in <b>grams</b>?", answer:"2450"},
    {topic:"Perimeter", text:"A rectangular garden has a perimeter of 74 m and a length of 21 m. What is its width?", html:"A rectangular garden has a <b>perimeter of 74 m</b> and a <b>length of 21 m</b>. What is its width?", answer:"16"}
  ];
})();
