window.SCHOLARSHIP_Y8_ARITH_T05 = (() => {
  const frac = (n,d) => `<span class="math-frac" aria-label="${n} over ${d}"><span class="top">${n}</span><span class="bottom">${d}</span></span>`;
  const mixed = (w,n,d) => `<span class="math-mixed"><span>${w}</span>${frac(n,d)}</span>`;

  return [
    {topic:"Whole Number Division", text:"A school receives 3,960 exercise books packed equally into boxes of 24. How many boxes are there?", html:"A school receives <b>3,960 exercise books</b> packed equally into boxes of <b>24</b>. How many boxes are there?", answer:"165"},
    {topic:"Estimation", text:"A warehouse sends 48 cartons. Each carton has a mass of 19.8 kg. Estimate the total mass by rounding 19.8 kg to the nearest kilogram before multiplying.", html:"A warehouse sends <b>48 cartons</b>. Each carton has a mass of <b>19.8 kg</b>. Estimate the total mass by <b>rounding 19.8 kg to the nearest kilogram</b> before multiplying.", answer:"960"},
    {topic:"Directed Numbers", text:"The temperature rises from -7°C in the morning to 13°C in the afternoon. By how many degrees does it rise?", html:"The temperature rises from <b>−7°C</b> in the morning to <b>13°C</b> in the afternoon. By how many degrees does it rise?", answer:"20"},
    {topic:"Remainders", text:"There are 587 students travelling by bus. Each bus holds 46 students. After filling as many buses as possible, how many students are left for the final bus?", html:"There are <b>587 students</b> travelling by bus. Each bus holds <b>46 students</b>. After filling as many buses as possible, how many students are left for the <b>final bus</b>?", answer:"35"},
    {topic:"Prime Factors", text:"A school wants to arrange 462 badges into equal rows, with a prime number of badges in each row. What is the greatest possible number of badges in each row?", html:"A school wants to arrange <b>462 badges</b> into equal rows, with a <b>prime number of badges in each row</b>. What is the greatest possible number of badges in each row?", answer:"11"},
    {topic:"Divisibility", text:"The number 47?2 must be divisible by 9. What digit replaces the question mark?", html:"The number <b>47?2</b> must be divisible by <b>9</b>. What digit replaces the question mark?", answer:"5"},

    {topic:"Fraction of a Quantity", text:"A library has 352 new books. 5/8 of them are fiction. How many fiction books are there?", html:`A library has <b>352 new books</b>. ${frac(5,8)} of them are fiction. How many fiction books are there?`, answer:"220"},
    {topic:"Fraction of a Remainder", text:"A shop has 420 notebooks. It sells 3/10 of them in the morning. In the afternoon it sells 2/7 of the notebooks that remain. How many notebooks are sold in the afternoon?", html:`A shop has <b>420 notebooks</b>. It sells ${frac(3,10)} of them in the morning. In the afternoon it sells ${frac(2,7)} of the notebooks that <b>remain</b>. How many notebooks are sold in the afternoon?`, answer:"84"},
    {topic:"Adding Fractions", text:"A tank is 2/5 full. Water equal to 1/4 of the tank's full capacity is then added. What fraction of the tank is now full? Give the answer in simplest form.", html:`A tank is ${frac(2,5)} full. Water equal to ${frac(1,4)} of the tank's <b>full capacity</b> is then added. What fraction of the tank is now full? Give the answer in <b>simplest form</b>.`, answer:"13/20", answerFormat:"fractionSimplest"},
    {topic:"Mixed Number Subtraction", text:"A rope is 6 1/3 m long. A piece 2 5/6 m long is cut off. How many metres of rope remain?", html:`A rope is ${mixed(6,1,3)} m long. A piece ${mixed(2,5,6)} m long is cut off. How many metres of rope remain?`, answer:"3 1/2"},
    {topic:"Mixed Number Multiplication", text:"A container holds 1 2/5 kg of rice. Five identical containers are filled. How many kilograms of rice are used altogether?", html:`A container holds ${mixed(1,2,5)} kg of rice. <b>Five identical containers</b> are filled. How many kilograms of rice are used altogether?`, answer:"7"},
    {topic:"Fraction Division", text:"A jug contains 4 1/2 L of juice. It is poured into cups that each hold 3/8 L. How many full cups can be filled?", html:`A jug contains ${mixed(4,1,2)} L of juice. It is poured into cups that each hold ${frac(3,8)} L. How many <b>full cups</b> can be filled?`, answer:"12"},

    {topic:"Decimal Multiplication", text:"Six identical lunch boxes cost $4.85 each. What is the total cost?", html:"Six identical lunch boxes cost <b>$4.85 each</b>. What is the total cost?", answer:"29.10"},
    {topic:"Decimal Division", text:"A bakery has 8.64 kg of dough. Each loaf uses 0.24 kg. How many loaves can be made?", html:"A bakery has <b>8.64 kg</b> of dough. Each loaf uses <b>0.24 kg</b>. How many loaves can be made?", answer:"36"},
    {topic:"Money", text:"Mia has $25.00. She spends $3.75 on a drink and $8.90 on lunch. How much money does she have left?", html:"Mia has <b>$25.00</b>. She spends <b>$3.75</b> on a drink and <b>$8.90</b> on lunch. How much money does she have left?", answer:"12.35"},
    {topic:"Rounding Decimals", text:"A walking track is measured as 18.746 km long. Round this length to the nearest tenth of a kilometre.", html:"A walking track is measured as <b>18.746 km</b> long. Round this length to the <b>nearest tenth of a kilometre</b>.", answer:"18.7"},

    {topic:"Percentage of a Quantity", text:"A Year 8 group has 240 students. 35% travel to school by bus. How many students travel by bus?", html:"A Year 8 group has <b>240 students</b>. <b>35%</b> travel to school by bus. How many students travel by bus?", answer:"84"},
    {topic:"Discount", text:"A bicycle helmet costs $180. It is discounted by 15%. What is the sale price?", html:"A bicycle helmet costs <b>$180</b>. It is discounted by <b>15%</b>. What is the sale price?", answer:"153"},
    {topic:"Percentage Increase", text:"A club has 320 members. Membership increases by 12.5%. How many members are there after the increase?", html:"A club has <b>320 members</b>. Membership increases by <b>12.5%</b>. How many members are there after the increase?", answer:"360"},
    {topic:"Percentage Decrease", text:"A water tank contains 480 L. Its contents decrease by 25%. How many litres remain?", html:"A water tank contains <b>480 L</b>. Its contents decrease by <b>25%</b>. How many litres remain?", answer:"360"},
    {topic:"Percentage to Fraction", text:"In a survey, 37.5% of students choose cycling. Write 37.5% as a fraction in simplest form.", html:"In a survey, <b>37.5%</b> of students choose cycling. Write <b>37.5%</b> as a <b>fraction in simplest form</b>.", answer:"3/8", answerFormat:"fractionSimplest"},
    {topic:"Fraction to Percentage", text:"A class completes 9/25 of a project on Monday. What percentage of the project is completed? Enter the number only.", html:`A class completes ${frac(9,25)} of a project on Monday. What <b>percentage</b> of the project is completed? Enter the number only.`, answer:"36"},

    {topic:"Ratio Sharing", text:"A prize of $540 is shared between Ana and Ben in the ratio 4 : 5. How much does Ben receive?", html:"A prize of <b>$540</b> is shared between Ana and Ben in the ratio <b>4 : 5</b>. How much does <b>Ben</b> receive?", answer:"300"},
    {topic:"Ratio Scaling", text:"A recipe uses flour and sugar in the ratio 5 : 2. If 750 g of flour is used, how many grams of sugar are needed?", html:"A recipe uses <b>flour : sugar = 5 : 2</b>. If <b>750 g of flour</b> is used, how many grams of sugar are needed?", answer:"300"},
    {topic:"Best Buy", text:"Pack A costs $13.50 for 6 items. Pack B costs $17.20 for 8 items. What is the difference in cost per item, in dollars?", html:"Pack A costs <b>$13.50 for 6 items</b>. Pack B costs <b>$17.20 for 8 items</b>. What is the <b>difference in cost per item, in dollars</b>?", answer:"0.10"},
    {topic:"Unit Rate", text:"A student reads 18 pages in 24 minutes at a steady rate. How many minutes will it take to read 45 pages at the same rate?", html:"A student reads <b>18 pages in 24 minutes</b> at a steady rate. How many minutes will it take to read <b>45 pages</b> at the same rate?", answer:"60"},

    {topic:"Speed", text:"A cyclist travels 27 km in 1 hour 30 minutes. What is the average speed in km/h?", html:"A cyclist travels <b>27 km</b> in <b>1 hour 30 minutes</b>. What is the average speed in <b>km/h</b>?", answer:"18"},
    {topic:"Distance", text:"A car travels at 64 km/h for 45 minutes. How far does it travel in kilometres?", html:"A car travels at <b>64 km/h</b> for <b>45 minutes</b>. How far does it travel in kilometres?", answer:"48"},
    {topic:"Travel Time", text:"A bus travels 156 km at an average speed of 52 km/h. How many minutes does the journey take?", html:"A bus travels <b>156 km</b> at an average speed of <b>52 km/h</b>. How many <b>minutes</b> does the journey take?", answer:"180"},
    {topic:"Elapsed Time", text:"A school activity starts at 09:47 and finishes at 12:25. How many minutes does it last?", html:"A school activity starts at <b>09:47</b> and finishes at <b>12:25</b>. How many <b>minutes</b> does it last?", answer:"158"},

    {topic:"Length Conversion", text:"One board is 2.35 m long and another is 680 mm long. What is their total length in centimetres?", html:"One board is <b>2.35 m</b> long and another is <b>680 mm</b> long. What is their total length in <b>centimetres</b>?", answer:"303"},
    {topic:"Mass Conversion", text:"A bag contains 3.6 kg of rice. After 850 g is used, how many grams remain?", html:"A bag contains <b>3.6 kg</b> of rice. After <b>850 g</b> is used, how many <b>grams</b> remain?", answer:"2750"},
    {topic:"Capacity Conversion", text:"A container holds 2.4 L of water. Another 750 mL is added. How many millilitres are in the container altogether?", html:"A container holds <b>2.4 L</b> of water. Another <b>750 mL</b> is added. How many <b>millilitres</b> are in the container altogether?", answer:"3150"},

    {topic:"Rectangle Area and Perimeter", text:"A rectangular garden has an area of 180 m² and a length of 15 m. What is its perimeter?", html:"A rectangular garden has an <b>area of 180 m²</b> and a <b>length of 15 m</b>. What is its perimeter?", answer:"54"},
    {topic:"Triangle Area", text:"A triangular flag has a base of 16 cm and a perpendicular height of 11 cm. What is its area in cm²?", html:"A triangular flag has a <b>base of 16 cm</b> and a <b>perpendicular height of 11 cm</b>. What is its area in <b>cm²</b>?", answer:"88"},
    {topic:"Parallelogram Area", text:"A parallelogram-shaped panel has a base of 13 cm and a perpendicular height of 8 cm. What is its area in cm²?", html:"A parallelogram-shaped panel has a <b>base of 13 cm</b> and a <b>perpendicular height of 8 cm</b>. What is its area in <b>cm²</b>?", answer:"104"},
    {topic:"Triangle Angles", text:"Two angles in a triangle are 47° and 68°. What is the third angle?", html:"Two angles in a triangle are <b>47°</b> and <b>68°</b>. What is the third angle?", answer:"65"},
    {topic:"Two-Step Money", text:"A school buys 4 packs of markers at $7.50 per pack and receives a $6 discount on the total. How much does the school pay?", html:"A school buys <b>4 packs of markers at $7.50 per pack</b> and receives a <b>$6 discount</b> on the total. How much does the school pay?", answer:"24"},
    {topic:"Map Scale", text:"On a map, 1 cm represents 5 km. Two towns are 7.4 cm apart on the map. What is the real distance between the towns in kilometres?", html:"On a map, <b>1 cm represents 5 km</b>. Two towns are <b>7.4 cm apart</b> on the map. What is the real distance between the towns in <b>kilometres</b>?", answer:"37"},

    {topic:"Rectangular Prism Volume", text:"A storage box measures 2.5 m by 1.2 m by 0.8 m. What is its volume in cubic metres?", html:"A storage box measures <b>2.5 m × 1.2 m × 0.8 m</b>. What is its volume in <b>m³</b>?", answer:"2.4"},
    {topic:"Volume and Capacity", text:"A rectangular tank measures 50 cm by 30 cm by 40 cm. What is its full capacity in litres?", html:"A rectangular tank measures <b>50 cm × 30 cm × 40 cm</b>. What is its full capacity in <b>litres</b>?", answer:"60"},

    {topic:"Mean", text:"Five daily step counts, measured in thousands of steps, are 12, 15, 18, 11 and 19. What is the mean? Give your answer in thousands of steps.", html:"Five daily step counts, measured in <b>thousands of steps</b>, are <b>12, 15, 18, 11 and 19</b>. What is the <b>mean</b>? Give your answer in <b>thousands of steps</b>.", answer:"15"},
    {topic:"Median", text:"Seven delivery times, in minutes, are 14, 9, 17, 12, 10, 16 and 11. What is the median time?", html:"Seven delivery times, in minutes, are <b>14, 9, 17, 12, 10, 16 and 11</b>. What is the <b>median</b> time?", answer:"12"},
    {topic:"Probability", text:"A bag contains 8 red, 12 blue and 5 green counters. One counter is chosen at random. What is the probability of choosing a green counter? Give the answer as a fraction in simplest form.", html:"A bag contains <b>8 red</b>, <b>12 blue</b> and <b>5 green</b> counters. One counter is chosen at random. What is the probability of choosing a <b>green</b> counter? Give the answer as a <b>fraction in simplest form</b>.", answer:"1/5", answerFormat:"fractionSimplest"},
    {topic:"Updated Mean", text:"The mean of 6 quiz scores is 14. A seventh score of 21 is added. What is the new mean?", html:"The mean of <b>6 quiz scores</b> is <b>14</b>. A seventh score of <b>21</b> is added. What is the new mean?", answer:"15"}
  ];
})();
