window.SCHOLARSHIP_Y8_ARITH_T08 = (() => {
  const frac = (n,d) => `<span class="math-frac" aria-label="${n} over ${d}"><span class="top">${n}</span><span class="bottom">${d}</span></span>`;
  const mixed = (w,n,d) => `<span class="math-mixed"><span>${w}</span>${frac(n,d)}</span>`;

  return [
    {topic:"Place Value", text:"A digital meter reads 52.764. What is the value of the digit 6?", html:"A digital meter reads <b>52.764</b>. What is the <b>value of the digit 6</b>?", answer:"0.06"},
    {topic:"Ordering Decimals", text:"Four runners record times of 12.48 s, 12.405 s, 12.50 s and 12.458 s. What is the fastest time?", html:"Four runners record times of <b>12.48 s</b>, <b>12.405 s</b>, <b>12.50 s</b> and <b>12.458 s</b>. What is the <b>fastest time</b>?", answer:"12.405"},
    {topic:"Divisibility", text:"A four-digit locker code is 43?8. What digit must replace ? so that the number is divisible by 9?", html:"A four-digit locker code is <b>43?8</b>. What digit must replace <b>?</b> so that the number is <b>divisible by 9</b>?", answer:"3"},
    {topic:"HCF", text:"A club has 96 red badges and 144 blue badges. They want to make the greatest possible number of identical packs with no badges left over. How many packs can they make?", html:"A club has <b>96 red badges</b> and <b>144 blue badges</b>. They want to make the <b>greatest possible number of identical packs</b> with no badges left over. How many packs can they make?", answer:"48"},
    {topic:"Simple Interest", text:"$1,500 is invested at 3% simple interest per year for 4 years. What is the total amount in the account after 4 years?", html:"<b>$1,500</b> is invested at <b>3% simple interest per year</b> for <b>4 years</b>. What is the <b>total amount</b> in the account after 4 years?", answer:"1680"},
    {topic:"Coordinates — Translation", text:"Point B is at (-4, 3). It moves 6 units to the right. What is its new x-coordinate?", html:"Point B is at <b>(−4, 3)</b>. It moves <b>6 units to the right</b>. What is its new <b>x-coordinate</b>?", answer:"2"},
    {topic:"Fraction of a Quantity", text:"A sports centre has 640 lockers. Five eighths are being used. How many lockers are being used?", html:`A sports centre has <b>640 lockers</b>. ${frac(5,8)} are being used. How many lockers are being used?`, answer:"400"},
    {topic:"Comparing Fractions", text:"Tank A is 7/12 full and Tank B is 5/8 full. By what fraction of a full tank is Tank B fuller than Tank A? Give your answer in simplest form.", html:`Tank A is ${frac(7,12)} full and Tank B is ${frac(5,8)} full. By what fraction of a <b>full tank</b> is Tank B fuller than Tank A? Give your answer in <b>simplest form</b>.`, answer:"1/24", answerFormat:"fractionSimplest"},
    {topic:"Equivalent Fractions", text:"A class has completed 11/15 of a project. Write this as an equivalent fraction with denominator 75. What is the numerator?", html:`A class has completed ${frac(11,15)} of a project. Write this as an <b>equivalent fraction with denominator 75</b>. What is the numerator?`, answer:"55"},
    {topic:"Mixed Number Addition", text:"One hiking trail is 2 3/4 km long and another is 1 5/6 km long. What is their total length in kilometres?", html:`One hiking trail is ${mixed(2,3,4)} km long and another is ${mixed(1,5,6)} km long. What is their <b>total length</b> in kilometres?`, answer:"4 7/12"},

    {topic:"Fraction Division", text:"A container holds 3 1/2 L of juice. It is poured equally into cups holding 1/4 L each. How many full cups can be filled?", html:`A container holds ${mixed(3,1,2)} L of juice. It is poured equally into cups holding ${frac(1,4)} L each. How many <b>full cups</b> can be filled?`, answer:"14"},
    {topic:"Decimal Money", text:"A student pays with $50 for an item costing $23.78. How much change should the student receive?", html:"A student pays with <b>$50</b> for an item costing <b>$23.78</b>. How much <b>change</b> should the student receive?", answer:"26.22"},
    {topic:"Decimal Multiplication", text:"Each bag of rice has a mass of 1.25 kg. What is the total mass of 6 bags?", html:"Each bag of rice has a mass of <b>1.25 kg</b>. What is the total mass of <b>6 bags</b>?", answer:"7.5"},
    {topic:"Percentage of a Quantity", text:"A school has 320 students in Year 8. If 22.5% are in the orchestra, how many students are in the orchestra?", html:"A school has <b>320 students</b> in Year 8. If <b>22.5%</b> are in the orchestra, how many students are in the orchestra?", answer:"72"},
    {topic:"Reverse Percentage", text:"A jacket costs $135 after a 25% discount. What was the original price?", html:"A jacket costs <b>$135</b> after a <b>25% discount</b>. What was the <b>original price</b>?", answer:"180"},
    {topic:"Percentage Increase", text:"A club has 480 members. Membership increases by 15%. How many members are there after the increase?", html:"A club has <b>480 members</b>. Membership increases by <b>15%</b>. How many members are there after the increase?", answer:"552"},
    {topic:"Ratio Sharing", text:"A $720 prize is shared in the ratio 5 : 3. How much does the person receiving the larger share get?", html:"A <b>$720 prize</b> is shared in the ratio <b>5 : 3</b>. How much does the person receiving the <b>larger share</b> get?", answer:"450"},
    {topic:"Simplifying Ratio", text:"A mixture contains 840 g of oats and 1.4 kg of nuts. When the ratio oats : nuts is simplified to 3 : n, what is n?", html:"A mixture contains <b>840 g of oats</b> and <b>1.4 kg of nuts</b>. When the ratio <b>oats : nuts</b> is simplified to <b>3 : n</b>, what is <b>n</b>?", answer:"5"},
    {topic:"Unit Rate", text:"Six movie tickets cost $51 altogether. What is the cost of one ticket?", html:"Six movie tickets cost <b>$51</b> altogether. What is the cost of <b>one ticket</b>?", answer:"8.5"},
    {topic:"Map Scale", text:"On a map, 1 cm represents 4 km. Two towns are 6.75 cm apart on the map. What is the actual distance in kilometres?", html:"On a map, <b>1 cm represents 4 km</b>. Two towns are <b>6.75 cm</b> apart on the map. What is the actual distance in <b>kilometres</b>?", answer:"27"},

    {topic:"Speed", text:"A car travels 157.5 km in 2.25 hours. What is its average speed in km/h?", html:"A car travels <b>157.5 km</b> in <b>2.25 hours</b>. What is its average speed in <b>km/h</b>?", answer:"70"},
    {topic:"Travel Time", text:"A cyclist travels 96 km at an average speed of 64 km/h. How many minutes does the journey take?", html:"A cyclist travels <b>96 km</b> at an average speed of <b>64 km/h</b>. How many <b>minutes</b> does the journey take?", answer:"90"},
    {topic:"Elapsed Time", text:"A workshop starts at 09:47 and finishes at 12:18. How many minutes does it last?", html:"A workshop starts at <b>09:47</b> and finishes at <b>12:18</b>. How many <b>minutes</b> does it last?", answer:"151"},
    {topic:"Mixed Length Units", text:"A walking route has one section 3.4 km long and another section 875 m long. What is the total length in metres?", html:"A walking route has one section <b>3.4 km</b> long and another section <b>875 m</b> long. What is the total length in <b>metres</b>?", answer:"4275"},
    {topic:"Mass Conversion", text:"A container holds 4.25 kg of flour. 780 g is used. How many grams remain?", html:"A container holds <b>4.25 kg</b> of flour. <b>780 g</b> is used. How many <b>grams</b> remain?", answer:"3470"},
    {topic:"Capacity and Division", text:"A jug contains 2.6 L of juice. The juice is shared equally among 8 bottles. How many millilitres go into each bottle?", html:"A jug contains <b>2.6 L</b> of juice. The juice is shared equally among <b>8 bottles</b>. How many <b>millilitres</b> go into each bottle?", answer:"325"},
    {topic:"Rectangle Area from Perimeter", text:"A rectangular garden has a perimeter of 74 m and a length of 22 m. What is its area in m²?", html:"A rectangular garden has a <b>perimeter of 74 m</b> and a <b>length of 22 m</b>. What is its area in <b>m²</b>?", answer:"330"},
    {topic:"Triangle Area", text:"A triangular sign has a base of 14.5 cm and a perpendicular height of 12 cm. What is its area in cm²?", html:"A triangular sign has a <b>base of 14.5 cm</b> and a <b>perpendicular height of 12 cm</b>. What is its area in <b>cm²</b>?", answer:"87"},
    {topic:"Square Area from Perimeter", text:"A square garden has a perimeter of 68 m. What is its area in m²?", html:"A square garden has a <b>perimeter of 68 m</b>. What is its area in <b>m²</b>?", answer:"289"},
    {topic:"Rectangular Prism Volume", text:"A storage box measures 8.5 cm by 6 cm by 4 cm. What is its volume in cm³?", html:"A storage box measures <b>8.5 cm × 6 cm × 4 cm</b>. What is its volume in <b>cm³</b>?", answer:"204"},

    {topic:"Angles Around a Point", text:"Three angles meet at a point. Two of the angles are 110° and 95°. What is the third angle?", html:"Three angles meet at a point. Two of the angles are <b>110°</b> and <b>95°</b>. What is the <b>third angle</b>?", answer:"155"},
    {topic:"Mean", text:"Five students read 18, 24, 21, 19 and 28 pages. What is the mean number of pages read?", html:"Five students read <b>18, 24, 21, 19</b> and <b>28</b> pages. What is the <b>mean</b> number of pages read?", answer:"22"},
    {topic:"Median", text:"Six delivery times, in minutes, are 13, 17, 9, 21, 15 and 11. What is the median?", html:"Six delivery times, in minutes, are <b>13, 17, 9, 21, 15</b> and <b>11</b>. What is the <b>median</b>?", answer:"14"},
    {topic:"Mode", text:"The numbers of goals scored in eight matches are 4, 6, 7, 6, 8, 6, 9 and 7. What is the mode?", html:"The numbers of goals scored in eight matches are <b>4, 6, 7, 6, 8, 6, 9</b> and <b>7</b>. What is the <b>mode</b>?", answer:"6"},
    {topic:"Range with Directed Numbers", text:"During one day, the lowest temperature is -5°C and the highest is 12°C. What is the temperature range in degrees Celsius?", html:"During one day, the lowest temperature is <b>−5°C</b> and the highest is <b>12°C</b>. What is the <b>temperature range</b> in degrees Celsius?", answer:"17"},
    {topic:"Mean from Total", text:"A cyclist rides a total of 136 km over 8 days. What is the mean distance ridden per day in kilometres?", html:"A cyclist rides a <b>total of 136 km</b> over <b>8 days</b>. What is the <b>mean distance</b> ridden per day in kilometres?", answer:"17"},
    {topic:"Probability", text:"A bag contains 5 red, 7 blue and 8 green counters. One counter is chosen at random. What is the probability of choosing a counter that is not green? Give your answer as a fraction in simplest form.", html:"A bag contains <b>5 red</b>, <b>7 blue</b> and <b>8 green</b> counters. One counter is chosen at random. What is the probability of choosing a counter that is <b>not green</b>? Give your answer as a <b>fraction in simplest form</b>.", answer:"3/5", answerFormat:"fractionSimplest"},
    {topic:"Probability Complement", text:"The probability of rain tomorrow is 0.35. What is the probability that it will not rain?", html:"The probability of rain tomorrow is <b>0.35</b>. What is the probability that it will <b>not rain</b>?", answer:"0.65"},
    {topic:"Estimation", text:"Four equipment items cost $398, $612, $197 and $805. Estimate the total cost by rounding each amount to the nearest hundred dollars.", html:"Four equipment items cost <b>$398</b>, <b>$612</b>, <b>$197</b> and <b>$805</b>. Estimate the total cost by rounding <b>each amount to the nearest hundred dollars</b>.", answer:"2000"},
    {topic:"Order of Operations — Money", text:"Four tickets cost $12 each. There is a $7 booking fee, then a $10 voucher is used. What is the final amount paid?", html:"Four tickets cost <b>$12 each</b>. There is a <b>$7 booking fee</b>, then a <b>$10 voucher</b> is used. What is the <b>final amount paid</b>?", answer:"45"},

    {topic:"Remainders", text:"A school has 1,000 stickers. They are packed into sheets of 36 stickers. After making as many full sheets as possible, how many stickers are left over?", html:"A school has <b>1,000 stickers</b>. They are packed into sheets of <b>36 stickers</b>. After making as many full sheets as possible, how many stickers are <b>left over</b>?", answer:"28"},
    {topic:"Discount", text:"A jacket is marked at $240 and is reduced by 15%. What is the sale price?", html:"A jacket is marked at <b>$240</b> and is reduced by <b>15%</b>. What is the <b>sale price</b>?", answer:"204"},
    {topic:"Fraction of a Remainder", text:"A library has 900 books. One third are on loan. Of the books that remain, one quarter are reserved. How many books are reserved?", html:`A library has <b>900 books</b>. ${frac(1,3)} are on loan. Of the books that <b>remain</b>, ${frac(1,4)} are reserved. How many books are reserved?`, answer:"150"},
    {topic:"Fraction to Decimal", text:"Seven twentieths of the students travel by bus. Write 7/20 as a decimal.", html:`${frac(7,20)} of the students travel by bus. Write ${frac(7,20)} as a <b>decimal</b>.`, answer:"0.35"},
    {topic:"Coordinates — Distance", text:"Point C is at (-3, -5) and point D is at (-3, 4). What is the distance between C and D in coordinate units?", html:"Point C is at <b>(−3, −5)</b> and point D is at <b>(−3, 4)</b>. What is the <b>distance</b> between C and D in coordinate units?", answer:"9"}
  ];
})();
