window.SCHOLARSHIP_Y8_ARITH_T07 = (() => {
  const frac = (n,d) => `<span class="math-frac" aria-label="${n} over ${d}"><span class="top">${n}</span><span class="bottom">${d}</span></span>`;
  const mixed = (w,n,d) => `<span class="math-mixed"><span>${w}</span>${frac(n,d)}</span>`;

  return [
    {topic:"Remainders", text:"A warehouse has 875 bottles. They are packed into boxes holding 24 bottles each. After as many full boxes as possible are packed, how many bottles are left over?", html:"A warehouse has <b>875 bottles</b>. They are packed into boxes holding <b>24 bottles each</b>. After as many full boxes as possible are packed, how many bottles are <b>left over</b>?", answer:"11"},
    {topic:"Percentage to Fraction", text:"In a survey, 37.5% of students chose option B. Write 37.5% as a fraction in simplest form.", html:"In a survey, <b>37.5%</b> of students chose option B. Write <b>37.5%</b> as a <b>fraction in simplest form</b>.", answer:"3/8", answerFormat:"fractionSimplest"},
    {topic:"Coordinates — Quadrants", text:"Point A has coordinates (-7, 4). In which quadrant is A? Enter 1, 2, 3 or 4.", html:"Point A has coordinates <b>(−7, 4)</b>. In which quadrant is A? Enter <b>1, 2, 3 or 4</b>.", answer:"2"},
    {topic:"Mixed Number Subtraction", text:"A roll of ribbon is 5 1/3 m long. A piece 2 5/6 m long is used. How many metres of ribbon remain?", html:`A roll of ribbon is ${mixed(5,1,3)} m long. A piece ${mixed(2,5,6)} m long is used. How many metres of ribbon remain?`, answer:"2 1/2"},
    {topic:"Simple Interest", text:"$1,200 is invested at 4% simple interest per year for 3 years. How much interest is earned?", html:"<b>$1,200</b> is invested at <b>4% simple interest per year</b> for <b>3 years</b>. How much <b>interest</b> is earned?", answer:"144"},
    {topic:"Whole Number Division", text:"A school orders 1,764 exercise books and packs them equally into 28 class boxes. How many books are placed in each box?", html:"A school orders <b>1,764 exercise books</b> and packs them equally into <b>28 class boxes</b>. How many books are placed in each box?", answer:"63"},
    {topic:"Decimal Addition", text:"Three items cost $18.75, $9.60 and $4.85. What is the total cost?", html:"Three items cost <b>$18.75</b>, <b>$9.60</b> and <b>$4.85</b>. What is the total cost?", answer:"33.20"},
    {topic:"Map Scale", text:"On a map, 1 cm represents 2.5 km. Two places are 8.4 cm apart on the map. What is the actual distance in kilometres?", html:"On a map, <b>1 cm represents 2.5 km</b>. Two places are <b>8.4 cm</b> apart on the map. What is the actual distance in <b>kilometres</b>?", answer:"21"},
    {topic:"Fraction Multiplication", text:"A tank is 7/8 full. A gardener uses 3/5 of the water currently in the tank. What fraction of the tank's full capacity is used? Give your answer in simplest form.", html:`A tank is ${frac(7,8)} full. A gardener uses ${frac(3,5)} of the water currently in the tank. What fraction of the tank's <b>full capacity</b> is used? Give your answer in <b>simplest form</b>.`, answer:"21/40", answerFormat:"fractionSimplest"},
    {topic:"Directed Numbers", text:"The temperature rises from -4°C in the morning to 9°C in the afternoon. By how many degrees does it rise?", html:"The temperature rises from <b>−4°C</b> in the morning to <b>9°C</b> in the afternoon. By how many degrees does it rise?", answer:"13"},

    {topic:"Rectangle Area and Perimeter", text:"A rectangular garden has an area of 252 m² and a length of 18 m. What is its perimeter?", html:"A rectangular garden has an <b>area of 252 m²</b> and a <b>length of 18 m</b>. What is its perimeter?", answer:"64"},
    {topic:"LCM", text:"Two shuttle buses leave a stop every 18 minutes and every 24 minutes. They leave together now. After how many minutes will they next leave together?", html:"Two shuttle buses leave a stop every <b>18 minutes</b> and every <b>24 minutes</b>. They leave together now. After how many minutes will they next leave together?", answer:"72"},
    {topic:"Percentage of a Quantity", text:"A school has 480 students. 17.5% are in the choir. How many students are in the choir?", html:"A school has <b>480 students</b>. <b>17.5%</b> are in the choir. How many students are in the choir?", answer:"84"},
    {topic:"Equivalent Fractions", text:"A class has completed 7/12 of a project. Write this as an equivalent fraction with denominator 60. What is the numerator?", html:`A class has completed ${frac(7,12)} of a project. Write this as an <b>equivalent fraction with denominator 60</b>. What is the numerator?`, answer:"35"},
    {topic:"Decimal Multiplication", text:"A water bottle holds 0.65 L. Four full bottles are poured into a container. How many litres of water are poured in altogether?", html:"A water bottle holds <b>0.65 L</b>. <b>Four</b> full bottles are poured into a container. How many <b>litres</b> of water are poured in altogether?", answer:"2.6"},
    {topic:"Adding Fractions", text:"A walking track has two sections measuring 3/8 km and 5/12 km. What is their total length in kilometres? Give your answer as a fraction in simplest form.", html:`A walking track has two sections measuring ${frac(3,8)} km and ${frac(5,12)} km. What is their total length in <b>kilometres</b>? Give your answer as a <b>fraction in simplest form</b>.`, answer:"19/24", answerFormat:"fractionSimplest"},
    {topic:"Rounding Whole Numbers", text:"A museum recorded 287,436 visitors. Round this number to the nearest thousand.", html:"A museum recorded <b>287,436 visitors</b>. Round this number to the <b>nearest thousand</b>.", answer:"287000"},
    {topic:"Fraction of a Remainder", text:"A shop has 720 notebooks. It sells 2/9 of them, then donates 3/7 of the notebooks that remain. How many notebooks are donated?", html:`A shop has <b>720 notebooks</b>. It sells ${frac(2,9)} of them, then donates ${frac(3,7)} of the notebooks that <b>remain</b>. How many notebooks are donated?`, answer:"240"},
    {topic:"Percentage Decrease", text:"A garden used 720 L of water on Monday. On Tuesday, water use was reduced by 12.5%. How many litres were used on Tuesday?", html:"A garden used <b>720 L</b> of water on Monday. On Tuesday, water use was reduced by <b>12.5%</b>. How many <b>litres</b> were used on Tuesday?", answer:"630"},
    {topic:"Mass Conversion", text:"A container holds 2.8 kg of flour. 650 g is used. How many grams remain?", html:"A container holds <b>2.8 kg</b> of flour. <b>650 g</b> is used. How many <b>grams</b> remain?", answer:"2150"},

    {topic:"Mean", text:"Six students read 12, 15, 9, 18, 11 and 13 books. What is the mean number of books read?", html:"Six students read <b>12, 15, 9, 18, 11</b> and <b>13</b> books. What is the <b>mean</b> number of books read?", answer:"13"},
    {topic:"Decimal Division", text:"A bakery has 7.56 kg of dough. Each loaf uses 0.28 kg. How many loaves can be made?", html:"A bakery has <b>7.56 kg</b> of dough. Each loaf uses <b>0.28 kg</b>. How many loaves can be made?", answer:"27"},
    {topic:"Ratio Sharing", text:"A $945 prize is shared in the ratio 4 : 5. How much does the person receiving the smaller share get?", html:"A <b>$945 prize</b> is shared in the ratio <b>4 : 5</b>. How much does the person receiving the <b>smaller share</b> get?", answer:"420"},
    {topic:"Whole Number Operations", text:"A small stadium has 28 rows with 36 seats in each row. If 85 seats are unavailable, how many seats are available?", html:"A small stadium has <b>28 rows</b> with <b>36 seats</b> in each row. If <b>85 seats</b> are unavailable, how many seats are available?", answer:"923"},
    {topic:"Triangle Area", text:"A triangular banner has a base of 17 cm and a perpendicular height of 12 cm. What is its area in cm²?", html:"A triangular banner has a <b>base of 17 cm</b> and a <b>perpendicular height of 12 cm</b>. What is its area in <b>cm²</b>?", answer:"102"},
    {topic:"Divisibility", text:"A four-digit code is 57?3. What digit must replace ? so that the number is divisible by 9?", html:"A four-digit code is <b>57?3</b>. What digit must replace <b>?</b> so that the number is <b>divisible by 9</b>?", answer:"3"},
    {topic:"Speed", text:"A van travels 126 km in 1.75 hours. What is its average speed in km/h?", html:"A van travels <b>126 km</b> in <b>1.75 hours</b>. What is its average speed in <b>km/h</b>?", answer:"72"},
    {topic:"Subtracting Fractions", text:"A water tank is 5/6 full. Then 1/4 of the tank's full capacity is used. What fraction of the tank's full capacity remains? Give your answer in simplest form.", html:`A water tank is ${frac(5,6)} full. Then ${frac(1,4)} of the tank's <b>full capacity</b> is used. What fraction of the tank's full capacity remains? Give your answer in <b>simplest form</b>.`, answer:"7/12", answerFormat:"fractionSimplest"},
    {topic:"Parallelogram Area", text:"A parallelogram-shaped sign has a base of 16.5 cm and a perpendicular height of 8 cm. What is its area in cm²?", html:"A parallelogram-shaped sign has a <b>base of 16.5 cm</b> and a <b>perpendicular height of 8 cm</b>. What is its area in <b>cm²</b>?", answer:"132"},
    {topic:"Percentage Increase", text:"A club has 640 members. Membership increases by 12.5%. How many members are there now?", html:"A club has <b>640 members</b>. Membership increases by <b>12.5%</b>. How many members are there now?", answer:"720"},

    {topic:"Best Buy", text:"Pack A contains 600 g of cereal and costs $4.20. Pack B contains 900 g and costs $5.85. How much cheaper per kilogram is Pack B? Give your answer in dollars.", html:"Pack A contains <b>600 g</b> of cereal and costs <b>$4.20</b>. Pack B contains <b>900 g</b> and costs <b>$5.85</b>. How much <b>cheaper per kilogram</b> is Pack B? Give your answer in <b>dollars</b>.", answer:"0.50"},
    {topic:"Elapsed Time", text:"A performance starts at 13:38 and finishes at 16:05. How many minutes does it last?", html:"A performance starts at <b>13:38</b> and finishes at <b>16:05</b>. How many <b>minutes</b> does it last?", answer:"147"},
    {topic:"Capacity Conversion", text:"A container holds 1.75 L of juice. Another 625 mL is added. How many millilitres are there altogether?", html:"A container holds <b>1.75 L</b> of juice. Another <b>625 mL</b> is added. How many <b>millilitres</b> are there altogether?", answer:"2375"},
    {topic:"Coordinates — Translation", text:"Point P starts at (2, -5). It moves 7 units left and 9 units up. What is its new y-coordinate?", html:"Point P starts at <b>(2, −5)</b>. It moves <b>7 units left</b> and <b>9 units up</b>. What is its new <b>y-coordinate</b>?", answer:"4"},
    {topic:"Reverse Percentage", text:"A pair of shoes is sold for $184 after a 20% discount. What was the original price?", html:"A pair of shoes is sold for <b>$184</b> after a <b>20% discount</b>. What was the original price?", answer:"230"},
    {topic:"Rounding Decimals", text:"A measurement is 6.7849 cm. Round it to 2 decimal places.", html:"A measurement is <b>6.7849 cm</b>. Round it to <b>2 decimal places</b>.", answer:"6.78"},
    {topic:"Mixed Length Units", text:"A walking route has one section 2.35 km long and another section 680 m long. What is the total length in metres?", html:"A walking route has one section <b>2.35 km</b> long and another section <b>680 m</b> long. What is the total length in <b>metres</b>?", answer:"3030"},
    {topic:"Ratio Scaling", text:"Red and blue paint are mixed in the ratio 3 : 8. If 960 mL of blue paint is used, how many millilitres of red paint are needed?", html:"Red and blue paint are mixed in the ratio <b>3 : 8</b>. If <b>960 mL of blue paint</b> is used, how many millilitres of red paint are needed?", answer:"360"},
    {topic:"Rectangular Prism Volume", text:"A storage box measures 12 cm by 7 cm by 5 cm. What is its volume in cm³?", html:"A storage box measures <b>12 cm × 7 cm × 5 cm</b>. What is its volume in <b>cm³</b>?", answer:"420"},
    {topic:"Fraction to Percentage", text:"In a team, 7 out of every 20 players are left-footed. What percentage of the players is this?", html:`In a team, ${frac(7,20)} of the players are left-footed. What <b>percentage</b> of the players is this?`, answer:"35"},

    {topic:"Perimeter", text:"A rectangular playground is 48 m long and 27 m wide. How many metres of fencing are needed to go once around the playground?", html:"A rectangular playground is <b>48 m</b> long and <b>27 m</b> wide. How many <b>metres of fencing</b> are needed to go once around the playground?", answer:"150"},
    {topic:"Updated Mean", text:"The mean of five quiz scores is 14. A sixth score of 20 is added. What is the mean of all six scores?", html:"The <b>mean of five quiz scores</b> is <b>14</b>. A sixth score of <b>20</b> is added. What is the mean of all six scores?", answer:"15"},
    {topic:"Fraction of a Quantity", text:"A library has 560 books. Three eighths of them are fiction. How many books are not fiction?", html:`A library has <b>560 books</b>. ${frac(3,8)} of them are fiction. How many books are <b>not fiction</b>?`, answer:"350"},
    {topic:"Range", text:"Seven delivery times, in minutes, are 8, 12, 17, 9, 21, 15 and 14. What is the range?", html:"Seven delivery times, in minutes, are <b>8, 12, 17, 9, 21, 15</b> and <b>14</b>. What is the <b>range</b>?", answer:"13"},
    {topic:"Probability", text:"A bag contains 9 red, 6 blue and 5 green counters. One counter is chosen at random. What is the probability of choosing a blue counter? Give your answer as a fraction in simplest form.", html:"A bag contains <b>9 red</b>, <b>6 blue</b> and <b>5 green</b> counters. One counter is chosen at random. What is the probability of choosing a <b>blue</b> counter? Give your answer as a <b>fraction in simplest form</b>.", answer:"3/10", answerFormat:"fractionSimplest"}
  ];
})();
