window.SCHOLARSHIP_Y8_ARITH_T03 = (() => {
  const frac = (n,d) => `<span class="math-frac" aria-label="${n} over ${d}"><span class="top">${n}</span><span class="bottom">${d}</span></span>`;
  const mixed = (w,n,d) => `<span class="math-mixed"><span>${w}</span>${frac(n,d)}</span>`;

  return [
    {topic:"Remainders", text:"A school has 1,157 badges and packs 24 badges in each box. How many badges are left over?", html:"A school has <b>1,157 badges</b> and packs <b>24 badges</b> in each box. How many badges are left over?", answer:"5"},
    {topic:"Unit Rate", text:"A 1.8 kg bag of rice costs $6.84. What is the cost per kilogram?", html:"A <b>1.8 kg</b> bag of rice costs <b>$6.84</b>. What is the cost per kilogram?", answer:"3.8"},
    {topic:"Directed Numbers", text:"A lift moves from level -3 in an underground car park to level 12. By how many levels does it rise?", html:"A lift moves from level <b>−3</b> in an underground car park to level <b>12</b>. By how many levels does it rise?", answer:"15"},
    {topic:"Fractions of a Remainder", text:"A 240 L tank is 3/4 full. Then 2/5 of the water currently in the tank is used. How many litres remain?", html:`A <b>240 L</b> tank is ${frac(3,4)} full. Then ${frac(2,5)} of the <b>water currently in the tank</b> is used. How many litres remain?`, answer:"108"},
    {topic:"Decimals", text:"Two runners finish in 12.640 seconds and 12.406 seconds. What is the difference between their times?", html:"Two runners finish in <b>12.640 seconds</b> and <b>12.406 seconds</b>. What is the difference between their times?", answer:"0.234"},
    {topic:"Estimation", text:"A shop buys 19.8 kg of nuts at $42.70 per kilogram. Round both numbers to the nearest whole number and use them to estimate the total cost.", html:"A shop buys <b>19.8 kg</b> of nuts at <b>$42.70 per kilogram</b>. Round <b>both numbers to the nearest whole number</b> and use them to estimate the total cost.", answer:"860"},
    {topic:"Divisibility", text:"A four-digit access code is 58?2. The code must be divisible by 9. What is the smallest digit that can replace ?", html:"A four-digit access code is <b>58?2</b>. The code must be <b>divisible by 9</b>. What is the smallest digit that can replace <b>?</b>?", answer:"3"},
    {topic:"Factors and Powers", text:"A warehouse has 432 bolts. Each box must contain the same number of bolts, and the number in each box must be a power of 2. What is the largest possible number of bolts in each box with none left over?", html:"A warehouse has <b>432 bolts</b>. Each box must contain the same number of bolts, and the number in each box must be a <b>power of 2</b>. What is the <b>largest possible</b> number of bolts in each box with none left over?", answer:"16"},
    {topic:"Time", text:"A train leaves at 09:47 and the journey takes 1 hour 38 minutes. What time does it arrive?", html:"A train leaves at <b>09:47</b> and the journey takes <b>1 hour 38 minutes</b>. What time does it arrive?", answer:"11:25", answers:["11:25","1125"]},
    {topic:"Profit Percentage", text:"A stall spends $240 on materials and sells all the finished items for $276. What is the profit as a percentage of the cost? Enter the number only.", html:"A stall spends <b>$240</b> on materials and sells all the finished items for <b>$276</b>. What is the <b>profit as a percentage of the cost</b>? Enter the number only.", answer:"15"},

    {topic:"GST", text:"A service costs $84 before GST. Add 15% GST. What is the total price?", html:"A service costs <b>$84 before GST</b>. Add <b>15% GST</b>. What is the total price?", answer:"96.6"},
    {topic:"Simple Interest", text:"$800 is invested at 4.5% simple interest per year for 2 years. How much interest is earned?", html:"<b>$800</b> is invested at <b>4.5% simple interest per year</b> for <b>2 years</b>. How much interest is earned?", answer:"72"},
    {topic:"Ratio Sharing", text:"A $500 prize is shared in the ratio 2 : 3 : 5. How much does the person receiving the largest share get?", html:"A <b>$500</b> prize is shared in the ratio <b>2 : 3 : 5</b>. How much does the person receiving the <b>largest share</b> get?", answer:"250"},
    {topic:"Length Conversion", text:"A rope is 2.35 m long and another piece is 84 cm long. What is their total length in centimetres?", html:"A rope is <b>2.35 m</b> long and another piece is <b>84 cm</b> long. What is their total length in <b>centimetres</b>?", answer:"319"},
    {topic:"Area Conversion", text:"A noticeboard has an area of 0.48 m². What is its area in cm²?", html:"A noticeboard has an area of <b>0.48 m²</b>. What is its area in <b>cm²</b>?", answer:"4800"},
    {topic:"Capacity", text:"A café has 3.6 L of juice and fills bottles that each hold 240 mL. How many full bottles can be filled?", html:"A café has <b>3.6 L</b> of juice and fills bottles that each hold <b>240 mL</b>. How many full bottles can be filled?", answer:"15"},
    {topic:"Mixed Numbers", text:"Two walking-track sections are 2 1/3 km and 1 5/8 km long. What is their total length?", html:`Two walking-track sections are ${mixed(2,1,3)} km and ${mixed(1,5,8)} km long. What is their total length?`, answer:"3 23/24"},
    {topic:"Fractions and Decimals", text:"A machine has a failure rate of 0.375. Write 0.375 as a fraction in simplest form.", html:"A machine has a failure rate of <b>0.375</b>. Write <b>0.375</b> as a <b>fraction in simplest form</b>.", answer:"3/8", answerFormat:"fractionSimplest"},
    {topic:"Percentage of a Remainder", text:"A 360-page book is read over two days. On Monday, 25% of the book is read. On Tuesday, 1/3 of the pages remaining after Monday are read. How many pages are still unread?", html:`A <b>360-page</b> book is read over two days. On Monday, <b>25%</b> of the book is read. On Tuesday, ${frac(1,3)} of the pages <b>remaining after Monday</b> are read. How many pages are still unread?`, answer:"180"},
    {topic:"Discount", text:"A sports bag costs $160 and is reduced by 22.5%. What is the sale price?", html:"A sports bag costs <b>$160</b> and is reduced by <b>22.5%</b>. What is the sale price?", answer:"124"},

    {topic:"Successive Percentages", text:"A club has 500 members. Membership increases by 8%, then the new total decreases by 10%. How many members are there after both changes?", html:"A club has <b>500 members</b>. Membership increases by <b>8%</b>, then the <b>new total</b> decreases by <b>10%</b>. How many members are there after both changes?", answer:"486"},
    {topic:"Probability and Expected Number", text:"The probability of winning a small prize in a game is 0.35. Over 200 trials, how many wins would be expected?", html:"The probability of winning a small prize in a game is <b>0.35</b>. Over <b>200 trials</b>, how many wins would be expected?", answer:"70"},
    {topic:"Median", text:"The numbers of deliveries made on five days are 18, 24, 21, 30 and 27. What is the median number of deliveries?", html:"The numbers of deliveries made on five days are <b>18, 24, 21, 30 and 27</b>. What is the <b>median</b> number of deliveries?", answer:"24"},
    {topic:"Mean", text:"Five water-use readings are 2.4 L, 2.7 L, 3.1 L, 3.4 L and 3.4 L. What is the mean reading in litres?", html:"Five water-use readings are <b>2.4 L, 2.7 L, 3.1 L, 3.4 L and 3.4 L</b>. What is the <b>mean</b> reading in litres?", answer:"3"},
    {topic:"Unit Price", text:"A 4.5 L container of paint costs $67.50. What is the cost per 100 mL?", html:"A <b>4.5 L</b> container of paint costs <b>$67.50</b>. What is the cost per <b>100 mL</b>?", answer:"1.5"},
    {topic:"Remainders", text:"A venue has 2,450 chairs and arranges them in rows of 36. How many chairs are left over after making as many complete rows as possible?", html:"A venue has <b>2,450 chairs</b> and arranges them in rows of <b>36</b>. How many chairs are left over after making as many complete rows as possible?", answer:"2"},
    {topic:"Cube Roots", text:"A cube-shaped storage box has a volume of 3375 cm³. What is the length of one edge?", html:"A cube-shaped storage box has a volume of <b>3375 cm³</b>. What is the length of one edge?", answer:"15"},
    {topic:"Powers", text:"A cell culture starts with 4 cells and then doubles six times. How many cells are there after the sixth doubling?", html:"A cell culture starts with <b>4 cells</b> and then <b>doubles six times</b>. How many cells are there after the sixth doubling?", answer:"256"},
    {topic:"Square Perimeter and Area", text:"A square garden has a perimeter of 96 m. What is its area in m²?", html:"A square garden has a <b>perimeter of 96 m</b>. What is its area in <b>m²</b>?", answer:"576"},
    {topic:"Trapezium Area", text:"A trapezium-shaped sign has parallel sides of 12 cm and 18 cm and a perpendicular height of 7 cm. What is its area in cm²?", html:"A trapezium-shaped sign has <b>parallel sides of 12 cm and 18 cm</b> and a <b>perpendicular height of 7 cm</b>. What is its area in <b>cm²</b>?", answer:"105"},

    {topic:"Angles", text:"Three angles around a point are 125°, 78° and x°. What is x?", html:"Three angles around a point are <b>125°</b>, <b>78°</b> and <b>x°</b>. What is <b>x</b>?", answer:"157"},
    {topic:"Currency Rate", text:"For a school trip, use the given rate NZ$1 = A$0.92. How many Australian dollars is NZ$250? Enter the number only.", html:"For a school trip, use the given rate <b>NZ$1 = A$0.92</b>. How many Australian dollars is <b>NZ$250</b>? Enter the number only.", answer:"230"},
    {topic:"Speed", text:"A van travels 150 km in 2 hours 30 minutes at a constant average speed. What is the average speed in km/h?", html:"A van travels <b>150 km</b> in <b>2 hours 30 minutes</b> at a constant average speed. What is the average speed in <b>km/h</b>?", answer:"60"},
    {topic:"Fractions of a Remainder", text:"Mia has $450. She spends 2/5 of it, then spends 1/3 of the money that remains. How much money is left?", html:`Mia has <b>$450</b>. She spends ${frac(2,5)} of it, then spends ${frac(1,3)} of the <b>money that remains</b>. How much money is left?`, answer:"180"},
    {topic:"Decimal Money", text:"Cheese costs $8.40 per kilogram. What is the cost of 1.25 kg?", html:"Cheese costs <b>$8.40 per kilogram</b>. What is the cost of <b>1.25 kg</b>?", answer:"10.5"},
    {topic:"Significant Figures", text:"A concert attendance is recorded as 58,746 people. Round this to 3 significant figures.", html:"A concert attendance is recorded as <b>58,746 people</b>. Round this to <b>3 significant figures</b>.", answer:"58700"},
    {topic:"Direct Proportion", text:"A recipe uses 450 g of flour for 6 servings. How much flour is needed for 14 servings at the same rate?", html:"A recipe uses <b>450 g</b> of flour for <b>6 servings</b>. How much flour is needed for <b>14 servings</b> at the same rate?", answer:"1050"},
    {topic:"Best Buy", text:"Pack A contains 750 g of cereal and costs $5.25. Pack B contains 1.2 kg and costs $7.92. How much cheaper per kilogram is Pack B than Pack A?", html:"Pack A contains <b>750 g</b> of cereal and costs <b>$5.25</b>. Pack B contains <b>1.2 kg</b> and costs <b>$7.92</b>. How much <b>cheaper per kilogram</b> is Pack B than Pack A?", answer:"0.4"},
    {topic:"Rate and Time", text:"A machine produces 2.4 components per second. How many components does it produce in 3.5 minutes?", html:"A machine produces <b>2.4 components per second</b>. How many components does it produce in <b>3.5 minutes</b>?", answer:"504"},
    {topic:"Ratio and Mass", text:"A 2.4 kg mixture is divided in the ratio 3 : 5. What is the mass of the larger share in grams?", html:"A <b>2.4 kg</b> mixture is divided in the ratio <b>3 : 5</b>. What is the mass of the <b>larger share</b> in <b>grams</b>?", answer:"1500"},

    {topic:"Divisibility and Remainders", text:"There are 742 prize cards. Cards are packed in bundles of 12. What is the smallest number of additional cards needed so that all cards can be packed with none left over?", html:"There are <b>742 prize cards</b>. Cards are packed in bundles of <b>12</b>. What is the <b>smallest number of additional cards</b> needed so that all cards can be packed with none left over?", answer:"2"},
    {topic:"Fraction Division", text:"A kitchen has 2 1/4 L of sauce. Each container holds 3/16 L. How many full containers can be filled?", html:`A kitchen has ${mixed(2,1,4)} L of sauce. Each container holds ${frac(3,16)} L. How many full containers can be filled?`, answer:"12"},
    {topic:"Percentages", text:"A school has 420 students. 35% travel by bus. How many students travel by bus?", html:"A school has <b>420 students</b>. <b>35%</b> travel by bus. How many students travel by bus?", answer:"147"},
    {topic:"Mass Conversion", text:"A parcel contains 3.75 kg of books and another 680 g item. What is the total mass in grams?", html:"A parcel contains <b>3.75 kg</b> of books and another <b>680 g</b> item. What is the total mass in <b>grams</b>?", answer:"4430"},
    {topic:"Elapsed Time", text:"A sports session starts at 13:35 and finishes at 16:08. How many minutes does the session last?", html:"A sports session starts at <b>13:35</b> and finishes at <b>16:08</b>. How many <b>minutes</b> does the session last?", answer:"153"}
  ];
})();
