window.SCHOLARSHIP_Y8_ARITH_T04 = (() => {
  const frac = (n,d) => `<span class="math-frac" aria-label="${n} over ${d}"><span class="top">${n}</span><span class="bottom">${d}</span></span>`;
  const mixed = (w,n,d) => `<span class="math-mixed"><span>${w}</span>${frac(n,d)}</span>`;

  return [
    {topic:"Place Value", text:"A parcel has a measured mass of 47.306 kg. What value does the digit 3 represent in kilograms?", html:"A parcel has a measured mass of <b>47.306 kg</b>. What value does the digit <b>3</b> represent in kilograms?", answer:"0.3"},
    {topic:"Ordering Decimals", text:"Four runners record times of 14.08 s, 14.8 s, 14.18 s and 14.008 s. What is the fastest time?", html:"Four runners record times of <b>14.08 s</b>, <b>14.8 s</b>, <b>14.18 s</b> and <b>14.008 s</b>. What is the <b>fastest time</b>?", answer:"14.008"},
    {topic:"Directed Numbers", text:"The temperature rises from -6°C before sunrise to 9°C in the afternoon. By how many degrees does it rise?", html:"The temperature rises from <b>−6°C</b> before sunrise to <b>9°C</b> in the afternoon. By how many degrees does it rise?", answer:"15"},
    {topic:"LCM", text:"Two shuttle buses leave a station every 18 minutes and every 24 minutes. If they leave together now, how many minutes will pass before they next leave together?", html:"Two shuttle buses leave a station every <b>18 minutes</b> and every <b>24 minutes</b>. If they leave together now, how many minutes will pass before they next leave together?", answer:"72"},
    {topic:"HCF", text:"A teacher has 84 red counters and 126 blue counters. She wants the greatest possible number of identical packs, with the same number of each colour in every pack and no counters left over. How many packs can she make?", html:"A teacher has <b>84 red counters</b> and <b>126 blue counters</b>. She wants the <b>greatest possible number of identical packs</b>, with the same number of each colour in every pack and no counters left over. How many packs can she make?", answer:"42"},
    {topic:"Fractions of a Quantity", text:"A box contains 320 beads. 3/8 are red and 1/4 are blue. The rest are white. How many white beads are there?", html:`A box contains <b>320 beads</b>. ${frac(3,8)} are red and ${frac(1,4)} are blue. The rest are white. How many white beads are there?`, answer:"120"},
    {topic:"Fractions of a Quantity", text:"A school has 264 Year 8 students. 7/12 take part in a winter sport. How many students take part?", html:`A school has <b>264 Year 8 students</b>. ${frac(7,12)} take part in a winter sport. How many students take part?`, answer:"154"},
    {topic:"Mixed Number Multiplication", text:"A soup recipe uses 1 3/4 L of stock for one large batch. How many litres of stock are needed for 6 batches?", html:`A soup recipe uses ${mixed(1,3,4)} L of stock for one large batch. How many litres of stock are needed for <b>6 batches</b>?`, answer:"10 1/2"},
    {topic:"Fraction Division", text:"A roll of ribbon is 5 1/4 m long. It is cut into pieces that are each 3/8 m long. How many complete pieces can be cut?", html:`A roll of ribbon is ${mixed(5,1,4)} m long. It is cut into pieces that are each ${frac(3,8)} m long. How many complete pieces can be cut?`, answer:"14"},
    {topic:"Decimal Division", text:"A bakery has 7.56 kg of dough and divides it equally into portions of 0.28 kg. How many portions are made?", html:"A bakery has <b>7.56 kg</b> of dough and divides it equally into portions of <b>0.28 kg</b>. How many portions are made?", answer:"27"},

    {topic:"Percentage to Fraction", text:"In a survey, 62.5% of students choose option A. Write 62.5% as a fraction in simplest form.", html:"In a survey, <b>62.5%</b> of students choose option A. Write <b>62.5%</b> as a <b>fraction in simplest form</b>.", answer:"5/8", answerFormat:"fractionSimplest"},
    {topic:"Fraction to Percentage", text:"A sports team wins 7 of its first 20 games. What percentage of the games has it won? Enter the number only.", html:"A sports team wins <b>7 of its first 20 games</b>. What <b>percentage</b> of the games has it won? Enter the number only.", answer:"35"},
    {topic:"Ratio", text:"A fruit drink is mixed in the ratio syrup : water = 4 : 7. A batch contains 660 mL altogether. How many millilitres of water are used?", html:"A fruit drink is mixed in the ratio <b>syrup : water = 4 : 7</b>. A batch contains <b>660 mL</b> altogether. How many millilitres of <b>water</b> are used?", answer:"420"},
    {topic:"Ratio Scaling", text:"A paint colour is made by mixing yellow and blue in the ratio 3 : 5. If 240 mL of yellow paint is used, how many millilitres of blue paint are needed?", html:"A paint colour is made by mixing <b>yellow : blue = 3 : 5</b>. If <b>240 mL of yellow</b> paint is used, how many millilitres of <b>blue</b> paint are needed?", answer:"400"},
    {topic:"Fuel Efficiency", text:"A car travels 420 km using 35 L of fuel. What is its average distance travelled per litre?", html:"A car travels <b>420 km</b> using <b>35 L</b> of fuel. What is its average distance travelled per litre?", answer:"12"},
    {topic:"Fuel Consumption", text:"A vehicle uses 7.5 L of fuel per 100 km. How many litres are needed for a 360 km trip at the same rate?", html:"A vehicle uses <b>7.5 L per 100 km</b>. How many litres are needed for a <b>360 km</b> trip at the same rate?", answer:"27"},
    {topic:"Wages", text:"A student works 7.5 hours at $24.80 per hour. How much does the student earn before tax?", html:"A student works <b>7.5 hours</b> at <b>$24.80 per hour</b>. How much does the student earn before tax?", answer:"186"},
    {topic:"Commission", text:"A salesperson earns 6% commission on sales of $4,500. How much commission is earned?", html:"A salesperson earns <b>6% commission</b> on sales of <b>$4,500</b>. How much commission is earned?", answer:"270"},
    {topic:"Markup", text:"A shop buys an item for $80 and sells it for $104. What is the markup as a percentage of the cost price? Enter the number only.", html:"A shop buys an item for <b>$80</b> and sells it for <b>$104</b>. What is the <b>markup as a percentage of the cost price</b>? Enter the number only.", answer:"30"},
    {topic:"Fractional Discount", text:"A jacket costs $150. During a sale, 3/10 of the original price is taken off. What is the sale price?", html:`A jacket costs <b>$150</b>. During a sale, ${frac(3,10)} of the original price is taken off. What is the sale price?`, answer:"105"},
    {topic:"Percentage Points", text:"A tablet battery is at 80% charge. Its charge level drops by 15 percentage points. What percentage charge remains? Enter the number only.", html:"A tablet battery is at <b>80%</b> charge. Its charge level drops by <b>15 percentage points</b>. What percentage charge remains? Enter the number only.", answer:"65"},

    {topic:"Mean from Total", text:"The mean of 8 daily sales figures is 14.5 items. How many items were sold altogether over the 8 days?", html:"The mean of <b>8 daily sales figures</b> is <b>14.5 items</b>. How many items were sold altogether over the 8 days?", answer:"116"},
    {topic:"Missing Value in Mean", text:"Five quiz scores have a mean of 76. Four of the scores are 72, 81, 69 and 78. What is the fifth score?", html:"Five quiz scores have a <b>mean of 76</b>. Four of the scores are <b>72, 81, 69 and 78</b>. What is the fifth score?", answer:"80"},
    {topic:"Range", text:"Five plant heights are 162 cm, 175 cm, 168 cm, 181 cm and 159 cm. What is the range of the heights?", html:"Five plant heights are <b>162 cm, 175 cm, 168 cm, 181 cm and 159 cm</b>. What is the <b>range</b> of the heights?", answer:"22"},
    {topic:"Median", text:"Six delivery times, in minutes, are 11, 13, 15, 18, 21 and 25. What is the median time?", html:"Six delivery times, in minutes, are <b>11, 13, 15, 18, 21 and 25</b>. What is the <b>median</b> time?", answer:"16.5"},
    {topic:"Probability", text:"A bag contains 18 red, 12 blue and 10 green counters. One counter is chosen at random. What is the probability of choosing a blue counter? Give the answer as a fraction in simplest form.", html:"A bag contains <b>18 red</b>, <b>12 blue</b> and <b>10 green</b> counters. One counter is chosen at random. What is the probability of choosing a <b>blue</b> counter? Give the answer as a <b>fraction in simplest form</b>.", answer:"3/10", answerFormat:"fractionSimplest"},
    {topic:"Circumference", text:"A circular wheel has a diameter of 70 cm. Using π = 22/7, find its circumference in centimetres.", html:`A circular wheel has a <b>diameter of 70 cm</b>. Using <b>π = ${frac(22,7)}</b>, find its circumference in centimetres.`, answer:"220"},
    {topic:"Semicircle Perimeter", text:"A semicircular sign has a diameter of 14 cm. Using π = 22/7, find the perimeter of the whole sign, including the straight diameter.", html:`A semicircular sign has a <b>diameter of 14 cm</b>. Using <b>π = ${frac(22,7)}</b>, find the perimeter of the <b>whole sign</b>, including the straight diameter.`, answer:"36"},
    {topic:"Parallelogram Area", text:"A parallelogram-shaped panel has a base of 18 cm and a perpendicular height of 11 cm. What is its area?", html:"A parallelogram-shaped panel has a <b>base of 18 cm</b> and a <b>perpendicular height of 11 cm</b>. What is its area?", answer:"198"},
    {topic:"Rectangle Area and Perimeter", text:"A rectangular garden has an area of 216 m² and a length of 18 m. What is its perimeter?", html:"A rectangular garden has an <b>area of 216 m²</b> and a <b>length of 18 m</b>. What is its perimeter?", answer:"60"},
    {topic:"Rectangular Prism Volume", text:"A storage crate measures 2.4 m by 1.5 m by 0.8 m. What is its volume in cubic metres?", html:"A storage crate measures <b>2.4 m × 1.5 m × 0.8 m</b>. What is its volume in <b>m³</b>?", answer:"2.88"},

    {topic:"Volume and Capacity", text:"An aquarium measures 60 cm by 40 cm by 35 cm. What is its capacity in litres?", html:"An aquarium measures <b>60 cm × 40 cm × 35 cm</b>. What is its capacity in <b>litres</b>?", answer:"84"},
    {topic:"Cylinder Volume", text:"A cylindrical container has radius 5 cm and height 12 cm. Using π = 3.14, what is its volume in cm³?", html:"A cylindrical container has <b>radius 5 cm</b> and <b>height 12 cm</b>. Using <b>π = 3.14</b>, what is its volume in <b>cm³</b>?", answer:"942"},
    {topic:"Square Roots", text:"A square courtyard has an area of 1521 m². What is the length of one side?", html:"A <b>square courtyard</b> has an area of <b>1521 m²</b>. What is the length of one side?", answer:"39"},
    {topic:"Pythagoras", text:"A rectangular screen is 9 cm high and 12 cm wide. What is the length of its diagonal?", html:"A rectangular screen is <b>9 cm high</b> and <b>12 cm wide</b>. What is the length of its diagonal?", answer:"15"},
    {topic:"Angles", text:"Two angles in a triangle are 52° and 68°. What is the third angle?", html:"Two angles in a triangle are <b>52°</b> and <b>68°</b>. What is the third angle?", answer:"60"},
    {topic:"Map Scale", text:"A map has a scale of 1 : 50,000. Two places are 7.2 cm apart on the map. What is the actual distance in kilometres?", html:"A map has a scale of <b>1 : 50,000</b>. Two places are <b>7.2 cm</b> apart on the map. What is the actual distance in <b>kilometres</b>?", answer:"3.6"},
    {topic:"Speed", text:"A cyclist travels 24 km in 1 hour 36 minutes. What is the average speed in km/h?", html:"A cyclist travels <b>24 km</b> in <b>1 hour 36 minutes</b>. What is the average speed in <b>km/h</b>?", answer:"15"},
    {topic:"Distance", text:"A bus travels at 72 km/h for 35 minutes. How far does it travel in kilometres?", html:"A bus travels at <b>72 km/h</b> for <b>35 minutes</b>. How far does it travel in kilometres?", answer:"42"},
    {topic:"Travel Time", text:"A car travels 180 km at an average speed of 75 km/h. How many minutes does the journey take?", html:"A car travels <b>180 km</b> at an average speed of <b>75 km/h</b>. How many <b>minutes</b> does the journey take?", answer:"144"},
    {topic:"Elapsed Time", text:"A workshop begins at 11:48 and ends at 14:17. How many minutes does it last?", html:"A workshop begins at <b>11:48</b> and ends at <b>14:17</b>. How many <b>minutes</b> does it last?", answer:"149"},

    {topic:"Mixed Length Units", text:"One board is 1.75 m long and another is 680 mm long. What is their total length in millimetres?", html:"One board is <b>1.75 m</b> long and another is <b>680 mm</b> long. What is their total length in <b>millimetres</b>?", answer:"2430"},
    {topic:"Decimal Money", text:"Fruit costs $6.40 per kilogram. What is the cost of 2.35 kg?", html:"Fruit costs <b>$6.40 per kilogram</b>. What is the cost of <b>2.35 kg</b>?", answer:"15.04"},
    {topic:"Arithmetic Sequence", text:"The first row of seats in a small auditorium has 18 seats. Each new row has 3 more seats than the row before it. How many seats are in the 12th row?", html:"The first row of seats in a small auditorium has <b>18 seats</b>. Each new row has <b>3 more seats</b> than the row before it. How many seats are in the <b>12th row</b>?", answer:"51"},
    {topic:"Density", text:"A metal sample has a mass of 540 g and a volume of 200 cm³. What is its density in g/cm³?", html:"A metal sample has a <b>mass of 540 g</b> and a <b>volume of 200 cm³</b>. What is its density in <b>g/cm³</b>?", answer:"2.7"}
  ];
})();
