window.SCHOLARSHIP_CATALOG = [
  {
    key: "Y4_ARITH_T01",
    year: "Y4",
    paper: "Arithmetic",
    test: "Test 1",
    version: "Written Answer",
    difficulty: "Very Easy",
    description: "Basic one-step arithmetic in simple everyday contexts. Multiplication and division use the 1–11 times tables only.",
    label: "Year 4 Arithmetic · Test 1 · Very Easy",
    durationMinutes: 45,
    questionsScript: "Y4/Arithmetic/Test01/questions.js",
    bankVar: "SCHOLARSHIP_Y4_ARITH_T01"
  },
  {
    key: "Y4_ARITH_T02",
    year: "Y4",
    paper: "Arithmetic",
    test: "Test 2",
    version: "Written Answer",
    difficulty: "Very Easy",
    description: "Basic one-step arithmetic in new everyday contexts. Multiplication and division use the 1–11 times tables only.",
    label: "Year 4 Arithmetic · Test 2 · Very Easy",
    durationMinutes: 45,
    questionsScript: "Y4/Arithmetic/Test02/questions.js",
    bankVar: "SCHOLARSHIP_Y4_ARITH_T02"
  },
  {
    key: "Y6_ARITH_T01",
    year: "Y6",
    paper: "Arithmetic",
    test: "Test 1",
    version: "Written Answer",
    label: "Year 6 Arithmetic · Test 1",
    durationMinutes: 45,
    questionsScript: "Y6/Arithmetic/Test01/questions.js",
    bankVar: "SCHOLARSHIP_Y6_ARITH_T01"
  },
  {
    key: "Y6_ARITH_T02",
    year: "Y6",
    paper: "Arithmetic",
    test: "Test 2",
    version: "Written Answer",
    label: "Year 6 Arithmetic · Test 2",
    durationMinutes: 45,
    questionsScript: "Y6/Arithmetic/Test02/questions.js",
    bankVar: "SCHOLARSHIP_Y6_ARITH_T02"
  },
  {
    key: "Y6_REASON_T01_MC",
    year: "Y6",
    paper: "Mathematical Reasoning",
    test: "Test 1",
    version: "Multiple Choice",
    label: "Year 6 Mathematical Reasoning · Test 1 · Multiple Choice",
    durationMinutes: 40,
    questionsScript: "Y6/Reasoning/MC/Test01/questions.js",
    bankVar: "SCHOLARSHIP_Y6_REASON_T01_MC",
    imageBase: "Y6/Reasoning/Shared/Test01"
  },
  {
    key: "Y6_REASON_T01_MIXED",
    year: "Y6",
    paper: "Mathematical Reasoning",
    test: "Test 1",
    version: "Mixed Response",
    label: "Year 6 Mathematical Reasoning · Test 1 · Mixed Response",
    durationMinutes: 40,
    questionsScript: "Y6/Reasoning/Mixed/Test01/questions.js",
    bankVar: "SCHOLARSHIP_Y6_REASON_T01_MIXED",
    imageBase: "Y6/Reasoning/Shared/Test01"
  },
  {
    key: "Y8_ARITH_T01",
    year: "Y8",
    paper: "Arithmetic",
    test: "Test 1",
    version: "Written Answer",
    difficulty: "Standard",
    label: "Year 8 Arithmetic · Test 1 · Standard",
    durationMinutes: 45,
    questionsScript: "Y8/Arithmetic/Test01/questions.js",
    bankVar: "SCHOLARSHIP_Y8_ARITH_T01"
  },
  {
    key: "Y8_ARITH_T02",
    year: "Y8",
    paper: "Arithmetic",
    test: "Test 2",
    version: "Written Answer",
    difficulty: "Standard",
    label: "Year 8 Arithmetic · Test 2 · Standard",
    durationMinutes: 45,
    questionsScript: "Y8/Arithmetic/Test02/questions.js",
    bankVar: "SCHOLARSHIP_Y8_ARITH_T02"
  },
  {
    key: "Y8_ARITH_T03",
    year: "Y8",
    paper: "Arithmetic",
    test: "Test 3",
    version: "Written Answer",
    difficulty: "Standard",
    label: "Year 8 Arithmetic · Test 3 · Standard",
    durationMinutes: 45,
    questionsScript: "Y8/Arithmetic/Test03/questions.js",
    bankVar: "SCHOLARSHIP_Y8_ARITH_T03"
  },
  {
    key: "Y8_ARITH_T04",
    year: "Y8",
    paper: "Arithmetic",
    test: "Test 4",
    version: "Written Answer",
    difficulty: "Standard",
    label: "Year 8 Arithmetic · Test 4 · Standard",
    durationMinutes: 45,
    questionsScript: "Y8/Arithmetic/Test04/questions.js",
    bankVar: "SCHOLARSHIP_Y8_ARITH_T04"
  },
  {
    key: "Y8_ARITH_T05",
    year: "Y8",
    paper: "Arithmetic",
    test: "Test 5",
    version: "Written Answer",
    difficulty: "Standard",
    label: "Year 8 Arithmetic · Test 5 · Standard",
    durationMinutes: 45,
    questionsScript: "Y8/Arithmetic/Test05/questions.js",
    bankVar: "SCHOLARSHIP_Y8_ARITH_T05"
  },
  {
    key: "Y8_ARITH_T06",
    year: "Y8",
    paper: "Arithmetic",
    test: "Test 6",
    version: "Written Answer",
    difficulty: "Standard",
    label: "Year 8 Arithmetic · Test 6 · Standard",
    durationMinutes: 45,
    questionsScript: "Y8/Arithmetic/Test06/questions.js",
    bankVar: "SCHOLARSHIP_Y8_ARITH_T06"
  },
  {
    key: "Y8_ARITH_T07",
    year: "Y8",
    paper: "Arithmetic",
    test: "Test 7",
    version: "Written Answer",
    difficulty: "Standard",
    label: "Year 8 Arithmetic · Test 7 · Standard",
    durationMinutes: 45,
    questionsScript: "Y8/Arithmetic/Test07/questions.js",
    bankVar: "SCHOLARSHIP_Y8_ARITH_T07"
  },
  {
    key: "Y8_ARITH_T08",
    year: "Y8",
    paper: "Arithmetic",
    test: "Test 8",
    version: "Written Answer",
    difficulty: "Standard",
    label: "Year 8 Arithmetic · Test 8 · Standard",
    durationMinutes: 45,
    questionsScript: "Y8/Arithmetic/Test08/questions.js",
    bankVar: "SCHOLARSHIP_Y8_ARITH_T08"
  },
  {
    key: "Y8_REASON_T01_MC",
    year: "Y8",
    paper: "Mathematical Reasoning",
    test: "Test 1",
    version: "Multiple Choice",
    label: "Year 8 Mathematical Reasoning · Test 1 · Multiple Choice",
    durationMinutes: 45,
    questionsScript: "Y8/Reasoning/MC/Test01/questions.js",
    bankVar: "SCHOLARSHIP_Y8_REASON_T01_MC",
    imageBase: "Y8/Reasoning/Shared/Test01"
  },
  {
    key: "Y8_REASON_T01_MIXED",
    year: "Y8",
    paper: "Mathematical Reasoning",
    test: "Test 1",
    version: "Mixed Response",
    label: "Year 8 Mathematical Reasoning · Test 1 · Mixed Response",
    durationMinutes: 45,
    questionsScript: "Y8/Reasoning/Mixed/Test01/questions.js",
    bankVar: "SCHOLARSHIP_Y8_REASON_T01_MIXED",
    imageBase: "Y8/Reasoning/Shared/Test01"
  }
];
