window.SCHOLARSHIP_Y8_ARITH_T06 = (() => {
  const frac = (n,d) => `<span class="math-frac" aria-label="${n} over ${d}"><span class="top">${n}</span><span class="bottom">${d}</span></span>`;
  const mixed = (w,n,d) => `<span class="math-mixed"><span>${w}</span>${frac(n,d)}</span>`;

  return [
    {topic:"Place Value", text:"A library records 406,275 visits in a year. What is the value of the digit 6?", html:"A library records <b>406,275 visits</b> in a year. What is the <b>value of the digit 6</b>?", answer:"6000"},
    {topic:"Fraction of a Quantity", text:"A sports centre has 336 lockers. 5/8 of them are in the main changing area. How many lockers are in the main changing area?", html:`A sports centre has <b>336 lockers</b>. ${frac(5,8)} of them are in the main changing area. How many lockers are in the main changing area?`, answer:"210"},
    {topic:"Coordinates — Quadrants", text:"Point A has coordinates (-5, -3). In which quadrant is A? Enter 1, 2, 3 or 4.", html:"Point A has coordinates <b>(−5, −3)</b>. In which quadrant is A? Enter <b>1, 2, 3 or 4</b>.", answer:"3"},
    {topic:"Discount", text:"A sports bag costs $240. It is discounted by 25%. What is the sale price?", html:"A sports bag costs <b>$240</b>. It is discounted by <b>25%</b>. What is the sale price?", answer:"180"},
    {topic:"Divisibility", text:"A four-digit code is 47?2. What digit must replace ? so that the number is divisible by 9?", html:"A four-digit code is <b>47?2</b>. What digit must replace <b>?</b> so that the number is <b>divisible by 9</b>?", answer:"5"},
    {topic:"Elapsed Time", text:"A workshop starts at 09:47 and finishes at 12:26. How many minutes does it last?", html:"A workshop starts at <b>09:47</b> and finishes at <b>12:26</b>. How many <b>minutes</b> does it last?", answer:"159"},
    {topic:"Simple Interest", text:"$900 is invested at 3.5% simple interest per year for 4 years. How much interest is earned?", html:"<b>$900</b> is invested at <b>3.5% simple interest per year</b> for <b>4 years</b>. How much <b>interest</b> is earned?", answer:"126"},
    {topic:"Ordering Decimals", text:"Four race times are 4.08 s, 4.8 s, 4.18 s and 4.108 s. What is the difference between the largest and smallest times?", html:"Four race times are <b>4.08 s, 4.8 s, 4.18 s</b> and <b>4.108 s</b>. What is the <b>difference between the largest and smallest times</b>?", answer:"0.72"},
    {topic:"HCF", text:"Two lengths of cord are 96 cm and 144 cm. They are cut into equal pieces of the greatest possible length with nothing left over. How long is each piece?", html:"Two lengths of cord are <b>96 cm</b> and <b>144 cm</b>. They are cut into equal pieces of the <b>greatest possible length</b> with nothing left over. How long is each piece?", answer:"48"},
    {topic:"Capacity Conversion", text:"A jug contains 2.4 L of juice. 650 mL is poured out. How many millilitres remain?", html:"A jug contains <b>2.4 L</b> of juice. <b>650 mL</b> is poured out. How many <b>millilitres</b> remain?", answer:"1750"},

    {topic:"Ratio Scaling", text:"Apple juice and orange juice are mixed in the ratio 4 : 7. If 560 mL of orange juice is used, how many millilitres of apple juice are needed?", html:"Apple juice and orange juice are mixed in the ratio <b>4 : 7</b>. If <b>560 mL of orange juice</b> is used, how many millilitres of apple juice are needed?", answer:"320"},
    {topic:"Directed Numbers", text:"An underground car park level is marked -3. A lift travels from level -3 to level 8. How many levels does it rise?", html:"An underground car park level is marked <b>−3</b>. A lift travels from level <b>−3</b> to level <b>8</b>. How many levels does it rise?", answer:"11"},
    {topic:"Mean from Total", text:"The mean number of books read by 6 students is 14. How many books did they read altogether?", html:"The <b>mean</b> number of books read by <b>6 students</b> is <b>14</b>. How many books did they read altogether?", answer:"84"},
    {topic:"Mixed Number Addition", text:"One walking track is 1 7/8 km long and another is 2 5/12 km long. What is their total length?", html:`One walking track is ${mixed(1,7,8)} km long and another is ${mixed(2,5,12)} km long. What is their total length?`, answer:"4 7/24"},
    {topic:"Percentage Increase", text:"A club has 320 members. Membership increases by 12.5%. How many members are there now?", html:"A club has <b>320 members</b>. Membership increases by <b>12.5%</b>. How many members are there now?", answer:"360"},
    {topic:"Area Conversion", text:"A display mat has an area of 2.35 m². What is its area in cm²?", html:"A display mat has an area of <b>2.35 m²</b>. What is its area in <b>cm²</b>?", answer:"23500"},
    {topic:"Coordinates — Distance", text:"Points B(4, -6) and C(4, 9) lie on the same vertical line. What is the distance between B and C?", html:"Points <b>B(4, −6)</b> and <b>C(4, 9)</b> lie on the same vertical line. What is the distance between B and C?", answer:"15"},
    {topic:"LCM", text:"Two warning lights flash every 14 seconds and every 21 seconds. They flash together now. After how many seconds will they next flash together?", html:"Two warning lights flash every <b>14 seconds</b> and every <b>21 seconds</b>. They flash together now. After how many seconds will they next flash together?", answer:"42"},
    {topic:"Unit Rate", text:"18 pens cost $31.50. What is the cost of one pen?", html:"<b>18 pens</b> cost <b>$31.50</b>. What is the cost of <b>one pen</b>?", answer:"1.75"},
    {topic:"Fraction of a Remainder", text:"A shop has 600 drink bottles. It sells 1/4 of them in the morning. It then donates 2/5 of the bottles that remain. How many bottles are donated?", html:`A shop has <b>600 drink bottles</b>. It sells ${frac(1,4)} of them in the morning. It then donates ${frac(2,5)} of the bottles that <b>remain</b>. How many bottles are donated?`, answer:"180"},

    {topic:"Estimation", text:"A school orders 48 packs of card. Each pack costs $19.70. Estimate the total cost by rounding $19.70 to the nearest dollar before multiplying.", html:"A school orders <b>48 packs</b> of card. Each pack costs <b>$19.70</b>. Estimate the total cost by <b>rounding $19.70 to the nearest dollar</b> before multiplying.", answer:"960"},
    {topic:"Map Scale", text:"On a map, 1 cm represents 4 km. Two towns are 7.5 cm apart on the map. What is the actual distance in kilometres?", html:"On a map, <b>1 cm represents 4 km</b>. Two towns are <b>7.5 cm</b> apart on the map. What is the actual distance in kilometres?", answer:"30"},
    {topic:"Simple Interest", text:"$1,500 is invested at 2% simple interest per year for 3 years. What is the total value of the investment after 3 years?", html:"<b>$1,500</b> is invested at <b>2% simple interest per year</b> for <b>3 years</b>. What is the <b>total value</b> of the investment after 3 years?", answer:"1590"},
    {topic:"Decimal Division", text:"A bakery has 12.6 kg of flour. Each batch uses 0.45 kg. How many batches can be made?", html:"A bakery has <b>12.6 kg</b> of flour. Each batch uses <b>0.45 kg</b>. How many batches can be made?", answer:"28"},
    {topic:"Probability", text:"A bag contains 7 red, 5 blue and 8 green counters. One counter is chosen at random. What is the probability of choosing a blue counter? Give the answer as a fraction in simplest form.", html:"A bag contains <b>7 red</b>, <b>5 blue</b> and <b>8 green</b> counters. One counter is chosen at random. What is the probability of choosing a <b>blue</b> counter? Give the answer as a <b>fraction in simplest form</b>.", answer:"1/4", answerFormat:"fractionSimplest"},
    {topic:"Rectangle Area and Perimeter", text:"A rectangular garden has an area of 192 m² and a length of 16 m. What is its perimeter?", html:"A rectangular garden has an <b>area of 192 m²</b> and a <b>length of 16 m</b>. What is its perimeter?", answer:"56"},
    {topic:"Percentage to Fraction", text:"In a survey, 62.5% of students chose option A. Write 62.5% as a fraction in simplest form.", html:"In a survey, <b>62.5%</b> of students chose option A. Write <b>62.5%</b> as a <b>fraction in simplest form</b>.", answer:"5/8", answerFormat:"fractionSimplest"},
    {topic:"Speed", text:"A runner travels 54 km in 1.5 hours. What is the average speed in km/h?", html:"A runner travels <b>54 km</b> in <b>1.5 hours</b>. What is the average speed in <b>km/h</b>?", answer:"36"},
    {topic:"Whole Numbers", text:"A school receives 24 boxes of 135 exercise books. It gives away 960 books. How many books remain?", html:"A school receives <b>24 boxes of 135 exercise books</b>. It gives away <b>960 books</b>. How many books remain?", answer:"2280"},
    {topic:"Coordinates — Translation", text:"Point P starts at (6, -2). It moves 9 units left and 7 units up. What is its new y-coordinate?", html:"Point P starts at <b>(6, −2)</b>. It moves <b>9 units left</b> and <b>7 units up</b>. What is its new <b>y-coordinate</b>?", answer:"5"},

    {topic:"Fraction Division", text:"A container holds 4 1/2 L of drink. Each bottle holds 3/8 L. How many full bottles can be filled?", html:`A container holds ${mixed(4,1,2)} L of drink. Each bottle holds ${frac(3,8)} L. How many <b>full bottles</b> can be filled?`, answer:"12"},
    {topic:"Median", text:"Seven delivery times, in minutes, are 6, 14, 9, 12, 18, 11 and 15. What is the median time?", html:"Seven delivery times, in minutes, are <b>6, 14, 9, 12, 18, 11</b> and <b>15</b>. What is the <b>median</b> time?", answer:"12"},
    {topic:"Mass Conversion", text:"A bag contains 4.75 kg of rice. Another 850 g is added. How many grams are in the bag altogether?", html:"A bag contains <b>4.75 kg</b> of rice. Another <b>850 g</b> is added. How many <b>grams</b> are in the bag altogether?", answer:"5600"},
    {topic:"Two-Step Money", text:"A group buys 8 tickets at $12.50 each and 3 parking passes at $6 each. What is the total cost?", html:"A group buys <b>8 tickets at $12.50 each</b> and <b>3 parking passes at $6 each</b>. What is the total cost?", answer:"118"},
    {topic:"Ratio Sharing", text:"A $720 prize is shared in the ratio 5 : 3. How much does the person receiving the smaller share get?", html:"A <b>$720 prize</b> is shared in the ratio <b>5 : 3</b>. How much does the person receiving the <b>smaller share</b> get?", answer:"270"},
    {topic:"Significant Figures", text:"A visitor count is recorded as 73,486. Round this number to 3 significant figures.", html:"A visitor count is recorded as <b>73,486</b>. Round this number to <b>3 significant figures</b>.", answer:"73500"},
    {topic:"Triangle Area", text:"A triangular sign has a base of 22 cm and a perpendicular height of 9 cm. What is its area in cm²?", html:"A triangular sign has a <b>base of 22 cm</b> and a <b>perpendicular height of 9 cm</b>. What is its area in <b>cm²</b>?", answer:"99"},
    {topic:"Travel Time", text:"A bus travels 96 km at an average speed of 64 km/h. How many minutes does the journey take?", html:"A bus travels <b>96 km</b> at an average speed of <b>64 km/h</b>. How many <b>minutes</b> does the journey take?", answer:"90"},
    {topic:"Missing Value from Mean", text:"The mean of five quiz scores is 16. Four of the scores are 14, 17, 12 and 19. What is the fifth score?", html:"The mean of <b>five quiz scores</b> is <b>16</b>. Four of the scores are <b>14, 17, 12</b> and <b>19</b>. What is the fifth score?", answer:"18"},
    {topic:"Best Buy", text:"Pack A contains 750 g and costs $5.10. Pack B contains 1.2 kg and costs $7.80. How much cheaper per kilogram is Pack B? Give your answer in dollars.", html:"Pack A contains <b>750 g</b> and costs <b>$5.10</b>. Pack B contains <b>1.2 kg</b> and costs <b>$7.80</b>. How much <b>cheaper per kilogram</b> is Pack B? Give your answer in <b>dollars</b>.", answer:"0.30"},

    {topic:"Prime Factors", text:"A teacher has 330 students and wants equal-sized teams, with a prime number of students in each team. What is the greatest possible prime number of students in each team?", html:"A teacher has <b>330 students</b> and wants equal-sized teams, with a <b>prime number</b> of students in each team. What is the <b>greatest possible prime number</b> of students in each team?", answer:"11"},
    {topic:"Reverse Percentage", text:"A pair of shoes is sold for $162 after a 10% discount. What was the original price?", html:"A pair of shoes is sold for <b>$162</b> after a <b>10% discount</b>. What was the original price?", answer:"180"},
    {topic:"Volume and Capacity", text:"A rectangular tank measures 50 cm by 30 cm by 40 cm. What is its full capacity in litres?", html:"A rectangular tank measures <b>50 cm × 30 cm × 40 cm</b>. What is its full capacity in <b>litres</b>?", answer:"60"},
    {topic:"Coordinates — Midpoint on an Axis", text:"Points (-8, 0) and (14, 0) lie on the x-axis. A third point lies exactly halfway between them. What is its x-coordinate?", html:"Points <b>(−8, 0)</b> and <b>(14, 0)</b> lie on the x-axis. A third point lies exactly <b>halfway between them</b>. What is its <b>x-coordinate</b>?", answer:"3"},
    {topic:"Order of Operations — Money", text:"A school buys 6 activity packs at $18 each and receives a $12 discount on the total. The remaining cost is shared equally by 4 clubs. How much does each club pay?", html:"A school buys <b>6 activity packs at $18 each</b> and receives a <b>$12 discount</b> on the total. The remaining cost is shared equally by <b>4 clubs</b>. How much does each club pay?", answer:"24"}
  ];
})();
