window.SCHOLARSHIP_Y8_ARITH_T01 = (() => {
  const frac = (n,d) => `<span class="math-frac" aria-label="${n} over ${d}"><span class="top">${n}</span><span class="bottom">${d}</span></span>`;
  const mixed = (w,n,d) => `<span class="math-mixed"><span>${w}</span>${frac(n,d)}</span>`;
  const root = (x) => `<span class="math-root" aria-label="square root of ${x}"><span class="radical">√</span><span class="radicand">${x}</span></span>`;
  const power = (b,e) => `<span class="math-power">${b}<sup>${e}</sup></span>`;

  return [
    {topic:"Whole Numbers", text:"A school library had 48,759 books and received 36,846 more. How many books are there now?", html:"A school library had <b>48,759</b> books and received <b>36,846</b> more. How many books are there now?", answer:"85605"},
    {topic:"Whole Numbers", text:"A charity has a $100,000 target and has raised $47,638. How many dollars are still needed?", html:"A charity has a <b>$100,000</b> target and has raised <b>$47,638</b>. How many dollars are still needed?", answer:"52362"},
    {topic:"Multiplication", text:"A supplier packs 248 boxes with 37 pencils in each box. How many pencils are packed altogether?", html:"A supplier packs <b>248</b> boxes with <b>37</b> pencils in each box. How many pencils are packed altogether?", answer:"9176"},
    {topic:"Division", text:"A school has 8,640 stickers and puts 48 stickers in each pack. How many complete packs can be made?", html:"A school has <b>8,640</b> stickers and puts <b>48</b> stickers in each pack. How many complete packs can be made?", answer:"180"},
    {topic:"Directed Numbers", text:"At dawn the temperature was -18°C. By midday it had risen by 35°C. What was the midday temperature?", html:"At dawn the temperature was <b>−18°C</b>. By midday it had risen by <b>35°C</b>. What was the midday temperature?", answer:"17"},
    {topic:"Order of Operations", text:"A club has 96 drink bottles. It keeps 36 aside and shares the rest equally among 5 teams. How many bottles does each team receive?", html:"A club has <b>96</b> drink bottles. It keeps <b>36</b> aside and shares the rest equally among <b>5</b> teams. How many bottles does each team receive?", answer:"12"},
    {topic:"Indices", text:"A digital branching pattern starts with 1 branch and then triples four times. How many branches are there after the fourth tripling?", html:`A digital branching pattern starts with <b>1 branch</b> and then <b>triples four times</b>. How many branches are there after the fourth tripling?`, answer:"81"},
    {topic:"Square Roots", text:"A square courtyard has an area of 2025 m². What is the length of one side?", html:`A square courtyard has an area of <b>2025 m²</b>. What is the length of one side?`, answer:"45"},
    {topic:"Rounding", text:"A city has a population of 384,762. Round this population to 2 significant figures.", html:"A city has a population of <b>384,762</b>. Round this population to <b>2 significant figures</b>.", answer:"380000"},
    {topic:"Rounding", text:"A measured mass is 17.486 kg. Round it to the nearest hundredth of a kilogram.", html:"A measured mass is <b>17.486 kg</b>. Round it to the <b>nearest hundredth</b> of a kilogram.", answer:"17.49"},

    {topic:"Factors and Multiples", text:"A teacher has 84 red counters and 126 blue counters. She wants to make the greatest possible number of groups so that every group has the same number of red counters and the same number of blue counters, with none left over. How many groups can she make?", html:"A teacher has <b>84 red counters</b> and <b>126 blue counters</b>. She wants the <b>greatest possible number of groups</b> so that every group has the same number of red counters and the same number of blue counters, with none left over. How many groups can she make?", answer:"42"},
    {topic:"Factors and Multiples", text:"Two shuttle buses leave together. One leaves every 18 minutes and the other every 24 minutes. After how many minutes will they next leave together?", html:"Two shuttle buses leave together. One leaves every <b>18 minutes</b> and the other every <b>24 minutes</b>. After how many minutes will they next leave together?", answer:"72"},
    {topic:"Prime Factors", text:"A competition has 286 students. They must be divided into equal-sized teams, and the number of students in each team must be a prime number. What is the largest possible team size?", html:"A competition has <b>286 students</b>. They must be divided into equal-sized teams, and the number of students in each team must be a <b>prime number</b>. What is the largest possible team size?", answer:"13"},
    {topic:"Factors", text:"All 72 chairs must be arranged in equal rows with no chairs left over. How many different positive whole-number choices are there for the number of rows?", html:"All <b>72 chairs</b> must be arranged in equal rows with no chairs left over. How many different <b>positive whole-number</b> choices are there for the number of rows?", answer:"12"},

    {topic:"Fractions", text:"A jug contains 5/6 L of apple juice and 7/9 L of orange juice is added. How many litres are in the jug altogether?", html:`A jug contains ${frac(5,6)} L of apple juice and ${frac(7,9)} L of orange juice is added. How many litres are in the jug altogether?`, answer:"1 11/18"},
    {topic:"Fractions", text:"A ribbon is 3 3/4 m long. A piece 1 5/6 m long is cut off. How many metres of ribbon remain?", html:`A ribbon is ${mixed(3,3,4)} m long. A piece ${mixed(1,5,6)} m long is cut off. How many metres of ribbon remain?`, answer:"1 11/12"},
    {topic:"Fractions", text:"12/35 of a garden is used for herbs. 7/8 of the herb section is basil. What fraction of the whole garden is basil?", html:`${frac(12,35)} of a garden is used for herbs. ${frac(7,8)} of the herb section is basil. What fraction of the <b>whole garden</b> is basil?`, answer:"3/10"},
    {topic:"Fractions", text:"A container holds 7/8 L of drink. Each serving is 7/32 L. How many full servings can be poured?", html:`A container holds ${frac(7,8)} L of drink. Each serving is ${frac(7,32)} L. How many <b>full servings</b> can be poured?`, answer:"4"},
    {topic:"Fractions", text:"A hall has 150 seats. 4/5 of the seats are occupied, and 2/3 of the people seated are adults. How many adults are seated?", html:`A hall has <b>150 seats</b>. ${frac(4,5)} of the seats are occupied, and ${frac(2,3)} of the people seated are adults. How many adults are seated?`, answer:"80"},
    {topic:"Fractions", text:"A water tank is 11/12 full. Water equal to 5/18 of the tank's capacity is used. What fraction of the tank is still full?", html:`A water tank is ${frac(11,12)} full. Water equal to ${frac(5,18)} of the tank's capacity is used. What fraction of the tank is still full?`, answer:"23/36"},
    {topic:"Fractions", text:"A walking track has two sections measuring 2 2/5 km and 3/4 km. What is the total length of these two sections?", html:`A walking track has two sections measuring ${mixed(2,2,5)} km and ${frac(3,4)} km. What is the total length of these two sections?`, answer:"3 3/20"},
    {topic:"Fractions", text:"In a school club, 7/9 of all the members equals 98 students. How many students are in the club altogether?", html:`In a school club, ${frac(7,9)} of all the members equals <b>98 students</b>. How many students are in the club altogether?`, answer:"126"},

    {topic:"Decimals", text:"Two parcels have masses of 18.407 kg and 6.985 kg. What is their total mass?", html:"Two parcels have masses of <b>18.407 kg</b> and <b>6.985 kg</b>. What is their total mass?", answer:"25.392"},
    {topic:"Decimals", text:"A 30 L container has 12.786 L removed. How many litres remain?", html:"A <b>30 L</b> container has <b>12.786 L</b> removed. How many litres remain?", answer:"17.214"},
    {topic:"Decimals", text:"Ribbon costs $0.35 per metre. What is the cost of 4.8 m of ribbon?", html:"Ribbon costs <b>$0.35 per metre</b>. What is the cost of <b>4.8 m</b> of ribbon?", answer:"1.68"},
    {topic:"Decimals", text:"A baker has 7.56 kg of flour and packs it into bags of 0.18 kg each. How many bags can be filled?", html:"A baker has <b>7.56 kg</b> of flour and packs it into bags of <b>0.18 kg</b> each. How many bags can be filled?", answer:"42"},
    {topic:"Fractions and Decimals", text:"A quality check shows that the probability of selecting a faulty item is 0.072. Write this probability as a fraction in simplest form.", html:"A quality check shows that the probability of selecting a faulty item is <b>0.072</b>. Write this probability as a <b>fraction in simplest form</b>.", answer:"9/125", answerFormat:"fractionSimplest"},
    {topic:"Decimals", text:"A café has 3.75 L of juice. Each small cup holds 0.025 L. How many full cups can be poured?", html:"A café has <b>3.75 L</b> of juice. Each small cup holds <b>0.025 L</b>. How many full cups can be poured?", answer:"150"},

    {topic:"Percentages", text:"A school has 360 students. 17.5% are in a sports programme. How many students are in the programme?", html:"A school has <b>360 students</b>. <b>17.5%</b> are in a sports programme. How many students are in the programme?", answer:"63"},
    {topic:"Reverse Percentages", text:"A club membership increased by 20% and is now 84 members. How many members were there before the increase?", html:"A club membership increased by <b>20%</b> and is now <b>84 members</b>. How many members were there before the increase?", answer:"70"},
    {topic:"Percentage Change", text:"The number of entries in a competition rose from 240 to 276. What was the percentage increase? Enter the number only.", html:"The number of entries in a competition rose from <b>240</b> to <b>276</b>. What was the <b>percentage increase</b>? Enter the number only.", answer:"15"},
    {topic:"Reverse Percentages", text:"After a 20% discount, a jacket costs $96. What was the original price?", html:"After a <b>20% discount</b>, a jacket costs <b>$96</b>. What was the original price?", answer:"120"},
    {topic:"Percentages", text:"A $180 sports bag is reduced by 20%. Later, the reduced price is increased by 10%. What is the final price?", html:"A <b>$180</b> sports bag is reduced by <b>20%</b>. Later, the reduced price is increased by <b>10%</b>. What is the final price?", answer:"158.4"},

    {topic:"Ratio", text:"A $234 prize fund is shared in the ratio 5 : 4 : 4. What is the largest share?", html:"A <b>$234</b> prize fund is shared in the ratio <b>5 : 4 : 4</b>. What is the largest share?", answer:"90"},
    {topic:"Rate", text:"A 7.5 kg bag of rice costs $27. What is the cost per kilogram?", html:"A <b>7.5 kg</b> bag of rice costs <b>$27</b>. What is the cost per kilogram?", answer:"3.6"},
    {topic:"Scale", text:"On a map with scale 1 : 25,000, two places are 8.4 cm apart. What is the real distance in kilometres?", html:"On a map with scale <b>1 : 25,000</b>, two places are <b>8.4 cm</b> apart. What is the real distance in kilometres?", answer:"2.1"},

    {topic:"Measurement", text:"A large display board has an area of 2.75 m². What is this area in cm²?", html:"A large display board has an area of <b>2.75 m²</b>. What is this area in <b>cm²</b>?", answer:"27500"},
    {topic:"Capacity", text:"A dispenser contains 4.6 L of water and another 375 mL is added. How many millilitres are there altogether?", html:"A dispenser contains <b>4.6 L</b> of water and another <b>375 mL</b> is added. How many millilitres are there altogether?", answer:"4975"},
    {topic:"Speed", text:"A car travels 168 km in 2 hours 24 minutes. What is its average speed in km/h?", html:"A car travels <b>168 km</b> in <b>2 hours 24 minutes</b>. What is its average speed in <b>km/h</b>?", answer:"70"},
    {topic:"Time", text:"A trip takes 2 hours 47 minutes in the morning and 1 hour 38 minutes in the afternoon. How many minutes of travel is this altogether?", html:"A trip takes <b>2 hours 47 minutes</b> in the morning and <b>1 hour 38 minutes</b> in the afternoon. How many <b>minutes</b> of travel is this altogether?", answer:"265"},

    {topic:"Circle Area", text:"A circular garden has radius 14 m. Using π = 22/7, what is its area in m²?", html:`A circular garden has radius <b>14 m</b>. Using π = ${frac(22,7)}, what is its area in <b>m²</b>?`, answer:"616"},
    {topic:"Triangle Area", text:"A triangular sign has base 12.5 cm and perpendicular height 8.4 cm. What is its area in cm²?", html:"A triangular sign has base <b>12.5 cm</b> and perpendicular height <b>8.4 cm</b>. What is its area in <b>cm²</b>?", answer:"52.5"},
    {topic:"Volume", text:"A storage box is 12 cm long, 7.5 cm wide and 4 cm high. What is its volume in cm³?", html:"A storage box is <b>12 cm</b> long, <b>7.5 cm</b> wide and <b>4 cm</b> high. What is its volume in <b>cm³</b>?", answer:"360"},
    {topic:"Surface Area", text:"A closed rectangular box measures 10 cm by 6 cm by 4 cm. What is its total surface area in cm²?", html:"A closed rectangular box measures <b>10 cm × 6 cm × 4 cm</b>. What is its total surface area in <b>cm²</b>?", answer:"248"},
    {topic:"Data", text:"Five quiz scores have a mean of 20. Four scores are 14, 17, 19 and 23. What is the fifth score?", html:"Five quiz scores have a <b>mean of 20</b>. Four scores are <b>14, 17, 19 and 23</b>. What is the fifth score?", answer:"27"}
  ];
})();
